### ISSUE TITLE
Default to HTTPS

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/documentation#100]
## Requirement - what kind of business use case are you trying to solve?

Redirect HTTP traffic to HTTPS

## Problem - what in Jaeger blocks you from solving the requirement?

Newer versions of Chrome (other browsers to follow) will start displaying a "this website is not secure" warning soon for websites not using HTTPS.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

On Netlify control panel, there's an option like this under "Domain management" / "HTTPS":

![image](https://user-images.githubusercontent.com/13387/42383137-a41ee664-8136-11e8-97ad-b2c85657252a.png)

**Comment by yurishkuro** [comment]
done
