### ISSUE TITLE
Rename JAEGER_SAMPLER_MANAGER_HOST_PORT to JAEGER_SAMPLING_ENDPOINT

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/documentation#124]
For each of the following linked tasks, change the documentation to include them. Add also a deprecation note on the description for the old name:

- [ ] https://github.com/jaegertracing/jaeger-client-go/issues/282
- [ ] https://github.com/jaegertracing/jaeger-client-java/issues/521

**Comment by Anisha-28** [comment]
Hi @jpkrohling if the issue is still open .. can i work on this issue .. and also can i get some clarity on this too

**Comment by jpkrohling** [comment]
This issue is still open! At this point, this is what needs to be done:

- [ ] check https://github.com/jaegertracing/jaeger/issues/1849 to determine which clients are using which end vars. Looks like Java is still on `JAEGER_SAMPLER_MANAGER_HOST_PORT`, but other languages might be using `JAEGER_SAMPLING_ENDPOINT` already.
- [ ] update the documentation to show the two env vars, and which clients support which
- [ ] alongside with `JAEGER_SAMPLER_MANAGER_HOST_PORT`, mention that future versions of the clients might use the new `JAEGER_SAMPLING_ENDPOINT` instead

**Comment by yurishkuro** [comment]
Bonus: fix remaining clients to use the single env var consistently.
