### ISSUE TITLE
How to dynamic set Trace sampling strategy?

### ISSUE THREAD

**Issue by wolfelven** [jaegertracing/documentation#125]
Hello, everyone。 I have a question when I was initialized trace configuration, the sampling strategy type was 'const'. How can I reset sampling strategy in agent or collector?

**Comment by yurishkuro** [comment]
you should not be initializing as const, leave sampling to the defaults and it will be pulled from the backend.

**Comment by yurishkuro** [comment]
no longer relevant, refer to OTEL SDK docs
