### ISSUE TITLE
Left-side menu overlaps content in center of page

### ISSUE THREAD

**Issue by genebean** [jaegertracing/documentation#127]
Opening this issue per @jpkrohling's request in Gitter... 
As shown in this screenshot, multiple menu entries on the left overlap the content in the center of the page. 
![image](https://user-images.githubusercontent.com/966789/44535305-ac0c7380-a6c7-11e8-815a-1fb5e7bf23ff.png)

**Comment by yurishkuro** [comment]
I think this is fixed.
