### ISSUE TITLE
Add troubleshooting page 

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/documentation#128]
## Requirement - what kind of business use case are you trying to solve?

We are seeing a lot of “cannot see spans” questions. Internally we have a troubleshooting guide we should make public to assist users with troubleshooting.

Convert blog post linked from https://www.jaegertracing.io/docs/1.13/troubleshooting/ to the actual docs

**Comment by jpkrohling** [comment]
cc @pgadige

**Comment by pgadige** [comment]
Thank you @jpkrohling ! I've begun working on it. Will get more inputs before making a PR.

**Comment by yurishkuro** [comment]
https://medium.com/jaegertracing/help-something-is-wrong-with-my-jaeger-installation-68874395a7a6

@jpkrohling your blog can go into this doc

**Comment by jpkrohling** [comment]
Would a reference to the blog post be better, or do you think that duplicating the content is worth it?

**Comment by yurishkuro** [comment]
Let’s start with the link so that we at least have a page in the docs. Longer term I think it would be better to have the content in the docs directly so that other people could edit it.

**Comment by yurishkuro** [comment]
Looking at the doc, I think one other aspect people often have issues with is _why_ the connections are not succeeding. We obviously cannot write an exhaustive troubleshooting for this, but perhaps there are some common mistakes?  I think one of them is people forget that when running in the container, the `localhost` that spans are sent to is probably not the way to reach the agent.
