### ISSUE TITLE
Document how Jaeger deals with data loss

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#136]
[Lennart asked][1]:

> Hi,
> 
> I am looking for more detailed information about Jaeger than can be found in the architecture docs. Where can I find this?
> 
> I am looking for answer to questions like:
> 
> - How does the collector ensure no trace data is lost; e.g. due to the storage being temporarily unavailable? does it have any buffering mechanism?
> - What will happen if storage becomes unavailable? Error reports, logging etc?
> - Details about the interfaces
> 
> Thanks
> Lennart
> 

[1]: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jaeger-tracing/4-8rCCV5ZZk/CxueoEc4BAAJ

**Comment by yurishkuro** [comment]
Jaeger does not **ensure** that no trace data is lost. On the contrary, it is designed to shed load by dropping data if the backend storage is unable to keep up. This design is applied in collectors, agents, and the client libraries: they each have an internal memory queue / buffer that is used to temporarily store the data while it's being sent/written to the lower level in the backend, and if that lower level is not fast enough then the queue overflows and the data is being dropped.

Dropping of data is reported via metrics in all components.

**Comment by Anisha-28** [comment]
HI @yurishkuro if the issue is still open .. i'll have a look into it .. i am an outreachy applicant

**Comment by yurishkuro** [comment]
@Anisha-28 have a go at it.

**Comment by Anisha-28** [comment]
Elasticsearch recommended over cassandra implements the search functionality on client side, if the storage becomes unavailable, jaeger client library sends the trace data to jaeger, system continues to run however when motion is detected, Error are reported in the log files.

**Comment by xuanvinhln** [comment]
Why don't we send data from jaeger-client directly to Kafka. There are two advantages to connecting a client directly to a Kafka. First, we have a larger buffet than the memory queue to prevent data loss when a large amount of span is generated. Second, writing data from Kafka into Elasticsearch can be slower in the case of Elasticsearch being overloaded.

**Comment by yurishkuro** [comment]
There are some reasons for agent documented in the FAQ https://www.jaegertracing.io/docs/1.20/faq/#do-i-need-to-run-jaeger-agent.

**Comment by xuanvinhln** [comment]
Hi @yurishkuro ,

In this architecture [,](https://www.jaegertracing.io/img/architecture-v2.png) in case I do not want to use Agent and Collector to save CPU and RAM resources (because I do not use sampling function). I think the jaeger-client should support sending data directly to Kafka.

**Comment by yurishkuro** [comment]
Feel free to propose a PR implementing a Reporter (or Sender) that sends to Kafka. There is no single "correct" way of sending data, all methods have pros and cons.

Closing since this is not a documentation issue any more.

**Comment by xuanvinhln** [comment]
Can you help me create an issue implementation the Reporter (or Sender) to Kafka? Give me the issue code for convenience tracking.
Thank you very much! @yurishkuro

**Comment by yurishkuro** [comment]
Not really sure that you're asking for. Go to the respective Jaeger client repository (they are linked from documentation site) and open a ticket there.

**Comment by xuanvinhln** [comment]
Thanks @yurishkuro
