### ISSUE TITLE
Remove 1.5 directory when releasing 1.7

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#143]
The files under 1.5 were just copies of the latest documentation as of 1.6, mostly as a testbed for docs versioning support. Some of those docs are not applicable to v1.5 due to breaking changes in 1.6.

Once we release 1.7, we should drop the 1.5 directory, and only maintain versioning from v1.6.

**Comment by lucperkins** [comment]
@yurishkuro We can safely exclude the 1.5 directory immediately if you'd like. Up to you.

**Comment by yurishkuro** [comment]
I know, but I think the versions drop-down will look odd with just 1.6

**Comment by lucperkins** [comment]
Ah, fair point. Sounds like a plan 👍🏻
