### ISSUE TITLE
Indicate which versions are beta, stable, etc.

### ISSUE THREAD

**Issue by lucperkins** [jaegertracing/documentation#151]
An intriguing suggestion from @BenHall in [this tweet](https://twitter.com/Ben_Hall/status/1039847746851807233): that we indicate which version(s) is/are stable, beta, production ready, etc. on the downloads page.

@yurishkuro This would be trivial to implement. Let me know which "tags" to apply to to the current versions (1.4.1, 1.5.0, and 1.6.0) on the downloads page and we can start there and put a simply system in place.

**Comment by yurishkuro** [comment]
I would rather drop old versions altogether and only show the latest, same as we do with Docker images. This minimizes the maintenance of this page, we only have a single var controlling the latest version for the whole site. We can add a link to GitHub Releases saying "older versions can be found here".

**Comment by lucperkins** [comment]
@yurishkuro Okay, I'll make that happen

**Comment by yurishkuro** [comment]
currently we don't have beta, stable, etc., all versions are stable. So going to close until the need arises.

**Comment by BenHall** [comment]
Then we would users be interested in 1.4? :)

Ben

**Comment by yurishkuro** [comment]
that's why I don't want to show old versions by default - they are still available "somewhere", but it's really an edge case when someone actually needs to pick an old version.
