### ISSUE TITLE
Update vulnerable dependency

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/documentation#155]
Looks like the `ffi` this project depends on has a security vulnerability:

![image](https://user-images.githubusercontent.com/13387/46151314-c3aebd00-c26e-11e8-91ab-1cb4a1725652.png)

![image](https://user-images.githubusercontent.com/13387/46151341-d75a2380-c26e-11e8-8c3e-384ff74865c4.png)

**Comment by jpkrohling** [comment]
Solution:
![image](https://user-images.githubusercontent.com/13387/46151401-fa84d300-c26e-11e8-8667-79fd2d3800df.png)

**Comment by yurishkuro** [comment]
I think this is no longer applicable.
