### ISSUE TITLE
Update document to add ES client certificate support

### ISSUE THREAD

**Issue by clyang82** [jaegertracing/documentation#161]
@clyang82 commented on [Fri Oct 26 2018](https://github.com/jaegertracing/jaeger/issues/1144)

## Requirement - what kind of business use case are you trying to solve?

https://github.com/jaegertracing/jaeger/issues/678

**Comment by yurishkuro** [comment]
@samudurand were you able to make AWS ES working with auth? (Ref: https://github.com/jaegertracing/jaeger/issues/1863#issuecomment-542104104)

**Comment by samudurand** [comment]
No, I made my ES node VPC based to limit the access
