### ISSUE TITLE
Static pull of Medium posts via web hook

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#165]
Currently we load Medium posts dynamically via AJAX on page load.

@lucperkins proposed (https://github.com/opentracing/opentracing.io/pull/366#issuecomment-436797984) doing it during build time (https://github.com/opentracing/opentracing.io/pull/368) and have an IFTTT call a Netlify web hook.

IMO, by itself it's not significantly different from what we already have, but one nice feature it would bring is that we won't have to update the link to the latest newsletter.

**Comment by lucperkins** [comment]
@yurishkuro I can take this on. I set up a hook in Netlify (you can see it [here](https://app.netlify.com/sites/jaegertracing/settings/deploys#build-hooks)) for it. I can handle everything on the site side 👍

**Comment by yurishkuro** [comment]
@lucperkins what about IFTTT rule, do we need to set up a shared account or something?

**Comment by lucperkins** [comment]
@yurishkuro In order to do that you need to be an owner of the Medium blog. The flow is basically:

* **IF** new Medium post is published
* **THEN** `POST` to webhook (to the URL specified in the Netlify hook, with an empty JSON string)
