### ISSUE TITLE
Rethink "next version" docs location

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#174]
We've run into this in the last release where all files were copied from 1.7 to 1.8 dir with simultaneous changes for the new features, which makes it difficult to review and track.

I would like to propose a different mechanism:
  * have a folder called `next-release` or something like that
    * changes for new features are made in that folder
    * there should be a way to see those docs rendered both in the Netlify PR builds and locally
    * on the main production site we can treat the `next-release` folder in one of two ways
      * never show on the main site
      * show if accessed by direct URL, but never show in the list of versions
  * when we cut a new release, it is just a straight copy from `next-release` to `major.minor` dir, without any additional changes (meaning we don't want to have special labels in the `next-release` files metadata indicating that they should be treated differently, the logic should only be based on the directory name).

If it is easier to implement, we don't have to keep these files in the `content/docs/next-release`, where they may be picked up by the version listing logic, we could pull them to a level higher, like `content/docs-next-release`. With that we may not even need any template changes at all.

cc @lucperkins @pavolloffay @jpkrohling

**Comment by pavolloffay** [comment]
+1. 

and also update release.md in the main repo with instructions to handle docs.

**Comment by jpkrohling** [comment]
`s/next-release/master` and I'm +1 :)

**Comment by yurishkuro** [comment]
@jpkrohling do you mean to call the directory "master"? That sounds odd.

**Comment by jpkrohling** [comment]
If the directory is named after a version, then `master` sounds appropriate

**Comment by pavolloffay** [comment]
I also like more `next-release` or `snapshot`we already publish images from master into `component-snapshot` repositories.
