### ISSUE TITLE
how to install jaeger without docker  on linux?

### ISSUE THREAD

**Issue by congim** [jaegertracing/documentation#177]
how to install jaeger without docker  on linux?  
I can't find cassandra sql file, and collector config file and standalone 、query service's config file.

**Comment by sidarth164** [comment]
Hi @yurishkuro, has there been any update on the above issue? I couldn't find any relevant docs on how to deploy a jaeger agent and collector using just binaries. I am working on a vm where docker containers are not supported.

**Comment by yurishkuro** [comment]
@jpkrohling wrote a blog post about this https://medium.com/jaegertracing/running-jaeger-agent-on-bare-metal-d1fc47d31fab

**Comment by Riyazghub** [comment]
Hi @jpkrohling, I would like to install jaeger-query and jaeger-collector using binaries separately on top of Ubuntu as a base image. I know that i can use direct jaeger images, But our organization doesn't support these images as Base images. How can i achieve this ? Do we have any examples ?

Sample Docker file:
```
FROM ubuntu:18.04
RUN apt-get update \
    && apt-get -y install curl \
    && curl -XGET jaeger-1.26.0-linux-amd64.tar.gz --output jaeger-1.26.0-linux-amd64.tar.gz \
    && tar -xvzf jaeger-1.26.0-linux-amd64.tar.gz \
    && mkdir -p /jaeger-query /var/lib/jaeger-query \
    && cp -R jaeger-1.26.0-linux-amd64/jaeger-query /usr/local/bin/ \
    && rm -rf jaeger-1.26.0-linux-amd64* \
    && chown appuser:appuser  /usr/local/bin/jaeger-query \
    && chown -R appuser:appuser  /jaeger-query \
    && chown appuser:appuser /var/lib/jaeger-query \
    && apt-get clean;

WORKDIR /jaeger-query

ENTRYPOINT [ "/usr/local/bin/jaeger-query" ]

EXPOSE 16685
EXPOSE 16686
EXPOSE 16687
ENV COLLECTOR_ZIPKIN_HOST_PORT=:9411
ENV SPAN_STORAGE_TYPE=elasticsearch
ENV ES_SERVER_URLS=ES_URL
```

**Comment by jpuskar** [comment]
The blog post above seems to have broken links to the actual codeblocks :(.
https://medium.com/jaegertracing/running-jaeger-agent-on-bare-metal-d1fc47d31fab

**Comment by jpkrohling** [comment]
@jpuskar, would you mind pasting a screenshot? I just checked, and the code blocks are printed correctly.

**Comment by jpuskar** [comment]
I just tried it again. It works from my personal phone, but fails from my corporate laptop. It must be a proxy issue on my side. Apologies that I didn't think to check this before posting. Thanks!
