### ISSUE TITLE
Add documentation for different sampling strategies available to clients

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/documentation#180]
Add this documentation to: http://jaeger.readthedocs.io/en/latest/client_libraries/

**Comment by yurishkuro** [comment]
Is this not addressed by https://www.jaegertracing.io/docs/1.8/sampling/ ?

**Comment by SaarthakMaini** [comment]
I think this issue can be closed as Jaeger Clients have been retired

**Comment by yurishkuro** [comment]
@SaarthakMaini actually, this one makes me think that it would be great to update the whole "client_libraries" page to describe features in OTEL SDKs. https://github.com/jaegertracing/documentation/issues/606
