### ISSUE TITLE
Missing client reporters' formats

### ISSUE THREAD

**Issue by yepninja** [jaegertracing/documentation#186]
## Requirement - what kind of business use case are you trying to solve?
Miscommunication about supported reporters' formats (compact or binary)

## Problem - what in Jaeger blocks you from solving the requirement?
The documentation section about client libraries' features has only joint property `report_jaeger_thrift_udp`.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Improve documentation by splitting property `report_jaeger_thrift_udp` to `report_jaeger_thrift_udp_compact` and `report_jaeger_thrift_udp_binary`

**Comment by yurishkuro** [comment]
Closing, as the request is not clear.  @yepninja if you think it's still an issue, please re-open and clarify which section of the site you're referring to (link would be good).
