### ISSUE TITLE
Clarification on supported Kafka version

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/documentation#189]
In the [Kafka storage backends](https://www.jaegertracing.io/docs/1.8/deployment/#kafka) documentation it says that version 0.8+ is supported.

However [Sarama Cluster](https://github.com/bsm/sarama-cluster) says it requires version 0.9+.

Wanted to clarify if 0.8 is still ok, or whether the documentation needs to be updated?

**Comment by objectiser** [comment]
cc @davit-y @ledor473

**Comment by yurishkuro** [comment]
@vprithvi

**Comment by vprithvi** [comment]
Good catch! We should update the documentation to read Kafka 0.9+ 
I think the initial version of the document mistook the minimum Sarama version (which is 0.8) to mean the minimum Kafka version, which would be the minimum of the Sarama and Sarama Cluster version.
