### ISSUE TITLE
Client libraries link is not correct

### ISSUE THREAD

**Issue by userimack** [jaegertracing/documentation#203]
## Requirement - what kind of business use case are you trying to solve?
Improving Documentation by providing right client-libraries link. 
At https://github.com/jaegertracing/documentation/blob/master/content/docs/1.8/getting-started.md#client-libraries
![screenshot 2019-01-14 at 6 07 52 pm](https://user-images.githubusercontent.com/12096062/51113412-de11a400-1827-11e9-8e06-b2c20a0fa71c.png)
Currently the link is pointing to: https://github.com/jaegertracing/documentation/blob/master/content/docs/client-libraries
which is not accessible.

## Problem - what in Jaeger blocks you from solving the requirement?
Resource Not Found Error

## Any open questions to address

For a solution is this a right link: https://github.com/jaegertracing/documentation/blob/master/content/docs/1.8/client-libraries.md Please confirm so that I will create a PR. Thanks

**Comment by objectiser** [comment]
When the files are used to generate the deployed [documentation](https://www.jaegertracing.io/docs/1.8/getting-started/#client-libraries), the link gets resolved correctly.

**Comment by userimack** [comment]
thanks and I am sorry for the confusion.
