### ISSUE TITLE
Clarify Kafka Documentation, specifically that it can't be used as a lone storage option.

### ISSUE THREAD

**Issue by dopry** [jaegertracing/documentation#207]
## Requirement - what kind of business use case are you trying to solve?

We were looking to quickly deploy jaeger using our existing kafka cluster as a backend. 

## Problem - what in Jaeger blocks you from solving the requirement?

When deploying jaeger-query we receive an error saying kafka was write only. The Documentation for version 1.9 doesn't indicate that kafka cannot serve as the span storage for jaeger-query. The Documentation for 1.6 does point out the limited capability 

> In version 1.6.0, the Kafka storage backend implementation only supports writing data, this means you will need to use another one (with the multiple storage types feature) to be able to view the traces in the Query component.
> 
> Starting from version 1.7.0, a new component (Ingester) will be added to support reading from Kafka and storing it in another storage backend (Elasticsearch or Cassandra).

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Amend the 1.9 and future documentation to note that Kafka is write-only storage and must be used in conjunction with ingester and another storage in order to support query.  It may make sense to rethink how Kafka's role is described. It's being used to queue transactions for storage, not actually as a storage backend.

**Comment by epkugelmass** [comment]
I was hit by this as well. The documentation as-is is quite confusing.

**Comment by yurishkuro** [comment]
Does #241 address your concerns?

**Comment by yurishkuro** [comment]
NB: I only added the explanation to the latest versions.
