### ISSUE TITLE
404 page not working in local development

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#216]
@lucperkins any idea why the 404 page doesn't render when running `make develop`?

**Comment by lucperkins** [comment]
@yurishkuro Are you navigating to /404.html?

**Comment by yurishkuro** [comment]
ok that one does show, but I was just trying non-existent URLs (it works on the live site)

**Comment by lucperkins** [comment]
Hugo doesn’t act as a standard web server, so going directly to the 404 page is the only way to access it locally

**Comment by yurishkuro** [comment]
Hugo has an issue since 2015, closed but not implemented: https://github.com/gohugoio/hugo/issues/874

**Comment by yurishkuro** [comment]
Closing since this isn't an issue with our setup.
