### ISSUE TITLE
No sidebar menu on mobile

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#224]
The top menu is folded into a button, but that only allows high level navigation. There seems to be no way to navigate between pages of the /docs.

@lucperkins

**Comment by lucperkins** [comment]
Would you want something like the [containerd docs](https://containerd.io/docs) have?

**Comment by yurishkuro** [comment]
Hard to compare, they don't have the same structure of the website. What I see in Jaeger is this:
  * on the Home page, the Docs top menu allows docs navigation and works fine in mobile
  * on any docs page, the Docs top menu item is removed, and replaced by Versions

Maybe we should simply keep the Docs menu always present at the top? It will be repeated in the sidebar in the desktop view. If we can find a way to hide Docs on /docs when not on mobile, then it would be ideal.
