### ISSUE TITLE
Autogenerate docs for options associated with each executable

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/documentation#227]
## Requirement - what kind of business use case are you trying to solve?

Provide documentation to show the available options for a Jaeger component.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently the options associated with each executable are only available by running the executable with the `help` parameter. This is not ideal when trying to configure a Jaeger deployment via (for example) the operator. It would be easy for users to reference a documentation page associated with the Jaeger component, version and optionally storage type (where relevant).

## Proposal - what do you suggest to solve the problem or improve the existing situation?

When a new version of Jaeger is released, and prior to the documentation for that version being published, a script could be executed that captures the usage message from the Jaeger components (per storage type), and performs some transformation to make it presentable.

**Comment by objectiser** [comment]
cc @JStickler @jpkrohling @pavolloffay

**Comment by tiffon** [comment]
I agree this would be useful. One possibility is to have a format similar to the client library features page.

**Comment by yurishkuro** [comment]
Duplicate of #250
