### ISSUE TITLE
Automate getting new contributors for the newsletter

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#237]

**Comment by jpkrohling** [comment]
I used to use this script for previous newsletters:
https://github.com/jpkrohling/list-first-time-contributors

The CNCF Dev Stats has since added the following:
https://jaeger.devstats.cncf.io/d/52/new-contributors-table?orgId=1&from=now-1M%2FM&to=now-1M%2FM

**Comment by jpkrohling** [comment]
I'm closing this one, as it's been a while since the last newsletter was published and I'm not sure we'll continue publishing it.
