### ISSUE TITLE
Add docs for jaeger operator labels support

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/documentation#259]
## Requirement - what kind of business use case are you trying to solve?

Add docs for labels support added in https://github.com/jaegertracing/jaeger-operator/pull/445

## Problem - what in Jaeger blocks you from solving the requirement?

Need to wait for #258 to be merged.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Include alongside resources, affinity, etc.

**Comment by jpkrohling** [comment]
@objectiser: this was done already, right?

**Comment by objectiser** [comment]
No hasn't been done yet: https://www.jaegertracing.io/docs/1.13/operator/#finer-grained-configuration
