### ISSUE TITLE
Document link patterns in UI configuration

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/documentation#272]
## Requirement - what kind of business use case are you trying to solve?

Provide documentation on configuring link patterns in the UI.

## Problem - what in Jaeger blocks you from solving the requirement?

No documentation currently exists.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add documentation to the https://www.jaegertracing.io/docs/latest/frontend-ui/#configuration section to explain how to configure links in the UI.

See https://medium.com/@mwieczorek/custom-links-in-jaeger-ui-3479f72bb815

**Comment by jpkrohling** [comment]
@mwieczorek would you like to take this one?

**Comment by objectiser** [comment]
Sorry, should have been closed by https://github.com/jaegertracing/documentation/pull/273.

**Comment by mwieczorek** [comment]
Yeah, I planned to do a PR next week but it looks like @objectiser was faster :)
Thanks.
