### ISSUE TITLE
Problem with --jaeger.tags

### ISSUE THREAD

**Issue by stel-lest** [jaegertracing/documentation#279]
https://www.jaegertracing.io/docs/1.13/deployment/

--jaeger.tags=key=value

I have specified this parameter. But the tag never appeared in trace.

**Comment by stel-lest** [comment]
![12](https://user-images.githubusercontent.com/28728029/61639247-c5d18480-aca3-11e9-9d9c-bdab9bbe8b83.PNG)
![1](https://user-images.githubusercontent.com/28728029/61639311-ec8fbb00-aca3-11e9-84a7-18afe65785c1.PNG)

**Comment by objectiser** [comment]
@stel-lest The tags added by the agent would appear until the `Process:` node - if you could expand that and see whether it is there?

**Comment by stel-lest** [comment]
@objectiser 
There is no tag. Here is screenshot.
![1](https://user-images.githubusercontent.com/28728029/61693277-efd48680-ad37-11e9-9a12-51ad05485025.PNG)
The launch parameters of the agent --jaeger.tags=key=value
:(

**Comment by objectiser** [comment]
@stel-lest What tags are listed under the `Process`?

**Comment by stel-lest** [comment]
@objectiser 
Sory, this is all tags:
![1](https://user-images.githubusercontent.com/28728029/61696531-2f9e6c80-ad3e-11e9-8592-5bcca344c7d8.PNG)

**Comment by objectiser** [comment]
@stel-lest I've tested using the all-in-one running in docker:
```
docker run -e COLLECTOR_ZIPKIN_HTTP_PORT=9411   -p 5775:5775/udp   -p 6831:6831/udp   -p 6832:6832/udp   -p 5778:5778   -p 16686:16686   -p 14268:14268   -p 9411:9411   jaegertracing/all-in-one:1.13 --jaeger.tags=hello=world
```
Starting up the jaeger-query UI and doing some searches generates some trace data that passes through the agent included in all-in-one, and causes the `hello=world` tag to show up in the traces. I also ran a service against this jaeger all-in-one and also saw the process tag:
![jaeger-tags-1](https://user-images.githubusercontent.com/164562/61785636-0811d780-ae04-11e9-9940-a3bf538c0bb7.png)

I then tried deploying Jaeger all-in-one to kubernetes using the jaeger-operator with the following CR:
```
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "my-jaeger"
spec:
  strategy: allInOne
  agent:
    options:
      jaeger:
        tags: hello=goodbye
```
which resulted in the following containers for one of my deployed services with auto-injected sidecar:
![jaeger-tags-2](https://user-images.githubusercontent.com/164562/61785589-ee709000-ae03-11e9-9eec-1e02a06afcda.png)
and resulting trace data
![jaeger-tags-3](https://user-images.githubusercontent.com/164562/61785603-f6303480-ae03-11e9-840d-f6dc84b75ad0.png)

So currently unable to reproduce your issue - can you compare your jaeger setup to the ones I have described to see what might be different?

**Comment by cash168** [comment]
start agent:jaeger-agent --log-level=debug --reporter.tchannel.host-port=jaeger.fbs:14267 --processor.jaeger-binary.server-host-port=localhost:6832 --processor.jaeger-compact.server-host-port=localhost:6831 --processor.zipkin-compact.server-host-port=localhost:5775 --jaeger.tags=hello=world

**Comment by cash168** [comment]
Starting agent:
jaeger-agent --log-level=debug --reporter.tchannel.host-port=jaeger.all.in.one.server:14267 --processor.jaeger-binary.server-host-port=localhost:6832 --processor.jaeger-compact.server-host-port=localhost:6831 --processor.zipkin-compact.server-host-port=localhost:5775 --jaeger.tags=hello=world

![image](https://user-images.githubusercontent.com/10704928/62518647-b53c1500-b832-11e9-81bd-ecd25fb3ca1e.png)

Tag "hello=world" not added
Tag "user_agent=22" added from jaeger-client (Go app)

**Comment by cash168** [comment]
jaeger-agent --log-level=debug --reporter.type=grpc --reporter.grpc.host-port=jaeger.all.in.one.server:14250 --processor.jaeger-binary.server-host-port=localhost:6832 --processor.jaeger-compact.server-host-port=localhost:6831 --processor.zipkin-compact.server-host-port=localhost:5775 --jaeger.tags=hello=world

![image](https://user-images.githubusercontent.com/10704928/62519395-262ffc80-b834-11e9-8de3-56c7c1f2513c.png)

Tag "hello=world" added!
Tag "user_agent=22" added from jaeger-client (Go app)!

**Comment by cash168** [comment]
--jaeger.tags works when used --reporter.type=grpc --reporter.grpc.host-port=host:port

**Comment by yurishkuro** [comment]
yes, as I recall it was only added to that code path, since we're planning to decommission tchannel. We should clarify the docs.
