### ISSUE TITLE
where to get jaeger-all-in-one install package for arm based linux? 

### ISSUE THREAD

**Issue by congzw** [jaegertracing/documentation#291]
## Problem
I need use  jaeger-all-in-one on arm based linux system, anybody knows where I can get the install package? Or how to achieve this goal?

## Proposal 
add a link to get the arm package or a document link for how to  achieve this goal?

**Comment by pavolloffay** [comment]
hi @congzw we do not build it by default. The support is tracked in this issue https://github.com/jaegertracing/jaeger/issues/1656. Please subscribe there.
