### ISSUE TITLE
Ingester docs port is deprecated

### ISSUE THREAD

**Issue by zhaopangithub** [jaegertracing/documentation#293]
https://www.jaegertracing.io/docs/1.13/deployment/#ingester
ingester Health check at / and Metrics endpoint port should be 14270 port ? 
 
![image](https://user-images.githubusercontent.com/16744923/63915449-b5fa4c80-ca68-11e9-9b58-cdf69fe29248.png)

**Comment by yurishkuro** [comment]
@pavolloffay please review

I chose to only update next-release, since we're planning to publish a new one soon.
