### ISSUE TITLE
K8S Operator yaml file broken! - jaegertracing_v1_jaeger_crd

### ISSUE THREAD

**Issue by amirbagh75** [jaegertracing/documentation#325]
this [link](https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing_v1_jaeger_crd.yaml) on this [page](https://www.jaegertracing.io/docs/1.15/operator/#installing-the-operator-on-kubernetes) return 404.
---
please change it to this link: [https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml](https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml)

**Comment by Jarnen** [comment]
returns 404 on this link  https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml

**Comment by Jarnen** [comment]
> ## this [link](https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing_v1_jaeger_crd.yaml) on this [page](https://www.jaegertracing.io/docs/1.15/operator/#installing-the-operator-on-kubernetes) return 404.
> please change it to this link: https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml

this new link also is now returning 404

**Comment by albertteoh** [comment]
Yes, I agree, looks like they've moved to different dirs possibly like:
- https://github.com/jaegertracing/jaeger-operator/tree/master/config/rbac
- https://github.com/jaegertracing/jaeger-operator/blob/master/config/crd/bases/jaegertracing.io_jaegers.yaml

@jpkrohling are you able to confirm please?
