### ISSUE TITLE
Wording about sampling on architecture page is confusing

### ISSUE THREAD

**Issue by KevinMGranger** [jaegertracing/documentation#340]
(note that this is separate from https://github.com/jaegertracing/documentation/issues/303, which is about the sampling mechanisms themselves-- not the introduction to the idea of sampling)

## Requirement - what kind of business use case are you trying to solve?

Advising fellow developers how and why to use the Jaeger client's sampling features.

## Problem - what in Jaeger blocks you from solving the requirement?

In the [Jaeger Client Libraries section of the Architecture page](https://www.jaegertracing.io/docs/1.16/architecture/#jaeger-client-libraries), sampling is mentioned as follows:

> ... Instead sampled spans are transmitted out of process asynchronously, in the background, to Jaeger Agents.

> The instrumentation has very little overhead, and is designed to be always enabled in production.

> _Note that while all traces are generated, only a few are sampled. Sampling a trace marks the trace for further processing and storage_. ...

(Emphasis mine). I think that part is confusing, especially when removed from the context of the prior sentences. Up until now, there hasn't been a separation of the idea of _generating_ a trace/span and _sending_ it. They've been one and the same.

I'm still not 100% sure I understand how it works myself, but as I understand it:

- typically one doesn't check sampling status-- you just keep constructing the span, adding tags, etc. as usual
- at the end, the library decides whether or not to send the span over
- this decision applies to all downstream spans (whether ChildOf or FollowsFrom), and is propagated across serialization boundaries via baggage items)

So, if I understand correctly, it's advised that folks ignore sampling status and just continue with the instrumentation code as usual. The previous sentence about instrumentation being low-cost implies this.

Put in pseudocode,

Not this:
```
if span.IsSampled {
    span.SetTag(...)
    span.End()
}
```
But this:
```
span.SetTag(...)
span.End() // library decides whether or not to send
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Reword the emphasized sentence to read something like:

> Note that while all traces are generated in the client library, only a few are sampled. Sampling means the trace is sent off to the Collector/Agent.

The very next sections are about Agents and the Collector, so it flows relatively well.

I'm definitely not married to that wording, so we can workshop it.

**Comment by yurishkuro** [comment]
@KevinMGranger does #342 help?

**Comment by KevinMGranger** [comment]
@yurishkuro yes, the new wording works wonderfully. Thank you!
