### ISSUE TITLE
Document jaeger-debug-id

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/documentation#349]
The feature is mentioned here https://www.jaegertracing.io/docs/1.16/client-features/ but it's not clear how it works. We have some more docs here https://github.com/jaegertracing/jaeger-client-java#via-http-headers

**Comment by fischerman** [comment]
@pavolloffay I was wondering what the implications of this feature are for the availability of Jaeger or the entire system in case of a (deliberate) high load on a service. This header seems to bypass measures like rate limiting, which I would consider important for the stability of the system. Is there any protection for that?

Components like the Kubernetes Nginx ingress controller don't have an option to disable this feature. As a workaround you could change the header name to something unknown.

**Comment by yurishkuro** [comment]
no longer needed, not supported by OTEL SDKs
