### ISSUE TITLE
Link to specific section needs scrolling back to the beginning of section

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/documentation#352]
When opening a link pointing directly to a page section, the browser is chopping off the beginning of the section. To read the the whole section, I need to scroll up a little bit. I believe this might have to do with the header, but that's just a guess.

Example URL: https://www.jaegertracing.io/docs/1.16/deployment/#storage-plugin
This is how it renders in Firefox 72.0.1 (Fedora 31):
![image](https://user-images.githubusercontent.com/13387/72814363-39f5e080-3c65-11ea-9c39-a15def89e923.png)

When the page is already rendered, I can click on the ToC item and it will jump to the right position:
![image](https://user-images.githubusercontent.com/13387/72814404-4aa65680-3c65-11ea-82b5-89511b931888.png)

**Comment by yurishkuro** [comment]
I am getting the opposite in Chrome, the page is scrolled up from the anchor:

![image](https://user-images.githubusercontent.com/3523016/72865764-ffad3300-3ca6-11ea-9c2d-e4108c431f0a.png)

cc @lucperkins
