### ISSUE TITLE
`make macos-setup` results in an error if Hugo is not installed

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/documentation#36]
After a fresh checkout, `make macos-setup` resulted in the following error:

```
$ make macos-setup
brew switch hugo 0.37.1 && brew link --overwrite hugo
Error: hugo not found in the Cellar.
make: *** [macos-setup] Error 2
```

Seems like it expects Hugo to be installed, already.

`make macos-setup` finished without error when I ran it after installing hugo.

**Comment by lucperkins** [comment]
@tiffon Somehow I thought that `brew switch` automatically installs if a tool is not present. I'll change the instructions.
