### ISSUE TITLE
Table of Contents can't be scrolled

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/documentation#360]
In the Operator documentation, the table of contents is now too big for the right-hand panel. Instead of allowing it to have a scroll, content is just being chopped off:

![image](https://user-images.githubusercontent.com/13387/74644699-f8c6f280-5176-11ea-9197-91fa72bdd526.png)

After "Removing an instance", there are still the following sections:

* Tracing the operator
* Monitoring the operator
* Uninstalling the operator

**Comment by lucperkins** [comment]
@jpkrohling I could make the TOC initially collapsed on specific pages if you'd like. Is that the kind of solution you had in mind?

**Comment by jpkrohling** [comment]
Not sure I had anything in mind, but I think the other possible option is to scroll the TOC along with the content. I think having the TOC collapsed is also a valid option. Or perhaps we should split the operator documentation?

**Comment by yurishkuro** [comment]
Another alternative, although probably a large change, is to merge the page ToC into the left sidebar and make the sidebar independently scrollable. It would provide a single consistent hierarchy of e documentation. It would also work well for pages like Client Features or CLi Flags, which are too wide to even use the right sidebar. 

In the mobile view, the TOC could be shown as expandable section at the top of the page.

**Comment by celestehorgan** [comment]
@kapunahelewong - can you take a look at this issue for the Jaeger team? :)

**Comment by kapunahelewong** [comment]
> @kapunahelewong - can you take a look at this issue for the Jaeger team? :)

Indeed!

**Comment by yurishkuro** [comment]
Same issue for left sidebar #508
