### ISSUE TITLE
Operator not created in correct namespace

### ISSUE THREAD

**Issue by esnible** [jaegertracing/documentation#373]
## Requirement - what kind of business use case are you trying to solve?

Install Jaeger from docs

## Problem - what in Jaeger blocks you from solving the requirement?

The documentation https://www.jaegertracing.io/docs/1.17/operator/ , and the earlier versions that I checked, tell the user to `kubectl create namespace observability` which "This creates the namespace used by default in the deployment files.".  This statement is incorrect; the deployment files have no namespace and the operator was created in my `default` names.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I propose the doc line `kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml` and the three that follow it include `-n observability`.

Alternately, the four yaml files should explicitly set `namespace: observability`.

**Comment by esnible** [comment]
Actually, ignore my solution.  I got the pod up, but it is endlessly logging

```
E0227 14:14:56.302298       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a/tools/cache/reflector.go:98: Failed to list *v1.ClusterRoleBinding: clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:observability:jaeger-operator" cannot list resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
```

At least one more things must be done to bring up the Jaeger Operator w/o OpenShift.

**Comment by jpkrohling** [comment]
For some reason, I missed the notification for this item. The PR #370 should have fixed this, but let me know if you think there's something else we need to change!
