### ISSUE TITLE
Integrate Jaeger Calendar into the website

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/documentation#383]
In order to bring visibility to our bi-weekly meeting and to encourage people to share their presentations about Jaeger, we could integrate the Jaeger Calendar into the website, possibly under the "Get in touch" page:

https://calendar.google.com/calendar/embed?src=77a1bva4sn9cm822r8oa03l2j0%40group.calendar.google.com

cc @pavolloffay, @objectiser

**Comment by JennySimen** [comment]
Hi, @jpkrohling!
I am an outreachy applicant for this cohort. Can I contribute to this issue?

**Comment by jpkrohling** [comment]
@JennySimen it's yours!
