### ISSUE TITLE
Incorrect value type used in kubernetes operator sampler param example

### ISSUE THREAD

**Issue by linjmeyer** [jaegertracing/documentation#386]
## Requirement - what kind of business use case are you trying to solve?

Configure a default sampling configuration using Jaeger operator

## Problem - what in Jaeger blocks you from solving the requirement?

The documentation (section is [Defining Sampling Strategies](https://www.jaegertracing.io/docs/1.16/operator/#defining-sampling-strategies)) shows an example of setting a 50% sampling rate as an integer (50).  This should be a double (0.5).

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Change 50 to 0.5.  I will send a PR as it's a small change.

**Comment by tiagonapoli** [comment]
@yurishkuro Just saw this - there's already a PR (I'm the one from https://github.com/jaegertracing/jaeger-client-node/issues/435)
