### ISSUE TITLE
How to update central sampling configuration dynamiclly

### ISSUE THREAD

**Issue by NareshBhanawat** [jaegertracing/documentation#388]
I am planning to use remote sampling configuration in my clients, which will then fetch the sampling config from agent using http://jaeger-agent:5778/sampling?service=ABC endpoint after some fixed interval. 

In some cases, I might want to update this central configuration at runtime based on some conditions. How to change it dynamically so that when the clients fetch it next time, they get the updated configuration? I could not find any information about it in the documentation (there is only a static file based configuration). Is there a PUT call allowed on sampling endpoint to update the sampling config for all services centrally? If so, what is the data format expected?

**Comment by yurishkuro** [comment]
There is a still-open PR to allow reloading sampling strategies from a file when the file changes. 

https://github.com/jaegertracing/jaeger/pull/2040
