### ISSUE TITLE
Sampling strategy for microservices with a frontend

### ISSUE THREAD

**Issue by NareshBhanawat** [jaegertracing/documentation#389]
## Requirement - what kind of business use case are you trying to solve?
Its not a bug or enhancement but a question - I have a kubernetes system, with an ingress and several microservices which I need to trace. I have added a probabilistic sampling config on ingress (fetching remotely).

I have a confusion regarding how to configure sampling strategy for it. Since all external requests come through ingress, where I have specified a sampling configuration, all the backend microservices will create child spans ingress span and will respect the sampling decision taken by ingress.

## Problem - Confusion regarding sampling strategy?
If that is the case, backend microservices will never make sampling decision and it should not matter what sampling strategy I provide there - as all requests come through ingress only - and I should need sampling strategy only for frontend service. Is this understanding correct ?

**Comment by yurishkuro** [comment]
At the moment Jaeger clients always respect sampling decision made at the root of the trace. If all your traces start at some gateway / ingress service, then all sampling decisions will be consolidated there.
