### ISSUE TITLE
How to disable or exclude the trace data of jaeger itself?

### ISSUE THREAD

**Issue by xiaolin8** [jaegertracing/documentation#394]
## How to disable or exclude the trace data of jaeger itself ?

**Comment by mohit-chawla** [comment]
+1 for mentioning this in the documentation

**Comment by yurishkuro** [comment]
documented https://www.jaegertracing.io/docs/1.17/monitoring/#traces

**Comment by mohit-chawla** [comment]
thank you @yurishkuro , happy to create PR next time.

**Comment by xuanvinhln** [comment]
how to disable it when I use jaeger-operator deployment

**Comment by smmileey** [comment]
How to disable it for Jaeger v2.1? Docs say that Jaeger has the ability to trace its own logs (https://www.jaegertracing.io/docs/2.1/monitoring/), but there's not a word on how to disable it.

**Comment by yurishkuro** [comment]
@smmileey thanks for raising, it was a regression in v2 docs. Fixed by #813.
