### ISSUE TITLE
Documentation for ES cron jobs provides incorrect examples

### ISSUE THREAD

**Issue by r0kas** [jaegertracing/documentation#396]
Following link provides incorrect example:
https://www.jaegertracing.io/docs/1.17/operator/#elasticsearch-rollover

```readTTL: 7d                                  // how long should be old data available for reading```

Generates errors in operator as non parsable here:

https://github.com/jaegertracing/jaeger-operator/blob/7d8f068277cc301c48abc935bb4b64774044286b/pkg/controller/jaeger/jaeger_controller.go#L211

Golang time package's Parse duration does not accept days:
https://golang.org/pkg/time/#ParseDuration

```Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".```

**Comment by pavolloffay** [comment]
I have moved it to docs repo.
