### ISSUE TITLE
Document one feasible way of scaling Tail-based Sampling with OTEL collector

### ISSUE THREAD

**Issue by ning2008wisc** [jaegertracing/documentation#422]
## Requirement - what kind of business use case are you trying to solve?
Scale Tail-based Sampling with correctness

## Problem - what in Jaeger blocks you from solving the requirement?

The current OTEL collector's Tail-based Sampling does not scale beyond 1 instance. To overcome this, either the users need to put a customized LB upfront with "Trace id" awareness or implement the "routing" feature based on "Trace id" within OTEL collector. Either way seems not straightforward

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Given that (1) the first release of documentation about OTEL components have been merged into Jaeger doc, (2) there is some discussion about using Kafka as a shuffling / buffering layer between the OTEL agent and OTEL collector, so that the spans (from OTEL agent) with the same Trace id should be produced to the same kafka topic partition. When OTEL collector consumes spans from the Kafka topic, the consumer threads from one OTEL collector will see all spans with same Trace id. The following is the initial draft of this proposal to scale Tail-based sampling

https://github.com/ning2008wisc/documentation/commit/f3d4b67c57c27ff0dd6807eae0fc32661a9f7a73

This proposal has been tested with certain load in scalable end-to-end setup to validate that all spans with same Trace id show up on only one OTEL collector (so that Tail-based sampling could be applied correctly).

If accepted, we could explicitly mark this proposal as one option, to seed more users to deploy and iterate it, or even come up with better option. Alternatively, this proposal can live in some other public channel, e.g. tech blog, initially targeted for a smaller scale of audience.

cc @yurishkuro @pavolloffay 
, t

**Comment by yurishkuro** [comment]
@annanay25 recently published how they shard OTEL collectors for multi-instance tail-based sampling (https://grafana.com/blog/2020/06/18/how-grafana-labs-enables-horizontally-scalable-tail-sampling-in-the-opentelemetry-collector/). I assume that logic will be eventually upstreamed.

While Kafka is a possible solution as well, using a persistent storage in front of the aggregating collectors is a significant bottleneck.

**Comment by ning2008wisc** [comment]
that seems really nice, closing this issue
