### ISSUE TITLE
One click edit on documentation

### ISSUE THREAD

**Issue by NiteshKoushik** [jaegertracing/documentation#426]
Unable to find one click edit on any of the jaeger documents, one click edit of documents will help user in changing the contents or adding new content if missed in the documents.

**Comment by NiteshKoushik** [comment]
Yes, I wish - I can try doing it.

**Comment by NiteshKoushik** [comment]
Any suggestions to proceed further ?

**Comment by yurishkuro** [comment]
This will require a small change in the Hugo templates used to render the pages, to provide an appropriate link to the Edit function on GitHub for the corresponding document.

@lucperkins have you done this before in other projects?

**Comment by NiteshKoushik** [comment]
Any updates.

**Comment by yurishkuro** [comment]
This should be resolved once we move to the docsy theme.
