### ISSUE TITLE
Copy feature in documents to copy code section

### ISSUE THREAD

**Issue by NiteshKoushik** [jaegertracing/documentation#427]
We can have a copy feature in every document, so that it would be easy for developers to copy the code section which is required.

I have gone through the below link of Hugo template copy function. I think this feature will be very helpful if it implemented.

https://wraihan.com/posts/syntax-highlighting-and-copy-function-in-hugo/

**Comment by yurishkuro** [comment]
Good idea. Do you want to create a pull request to apply this?

**Comment by NiteshKoushik** [comment]
Yes.. If the changes made globally in the document, I can change every code section where ever it is required.

**Comment by yurishkuro** [comment]
we already have this
