### ISSUE TITLE
Rethink blog

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#428]
I like Medium for authoring and its "social" aspects, but I really dislike how difficult it makes finding older blog posts. And we had a lot of great old posts that discuss architecture and deployment modes of Jaeger, which I think people are completely missing. I think we need to rethink how we maintain the blog posts. Some options:

* host all posts in this repo
  * pros:
    * authoring in Markdown is just as easy
  * cons: 
    * inserting images is somewhat harder
    * lacking "social" aspects, like following specific authors, or even reading posts by a given author (possible by will require some Hugo templating changes)
* continue hosting on Medium, but maintain an index on the website (more extensive than the carousel on the home page).
  * we could build index automatically similar to the carousel
* convert some of the blog posts into official documentation (e.g. discussion on multi-tenancy, etc.)
  * this could also take form of an extended FAQ section with direct links to the blog posts on Medium

**Comment by yurishkuro** [comment]
@jaegertracing/jaeger-maintainers

**Comment by JStickler** [comment]
Blog posts should be more for advertising the project to people who may not have heard about it, marketing new features to get feedback, that sort of thing.  If there's content like architecture and deployment information in blog posts, that should definitely be converted to documentation.

**Comment by objectiser** [comment]
The second two options sound good - so have a better index, but for certain topics (as Julie suggests) we use the blog content as the basis for starting a topic in the documentation, and then reference that from the blog post.

**Comment by jpkrohling** [comment]
To me, the social aspect is the only thing that keeps us at Medium. Pretty much everything else is better with adoc/markdown, especially code snippets.

A mix of 2 and 3 is also good for me: move some of the blog posts to documentation pages, with a better indexing for the existing posts.

As a starting point, here's a selection of blog posts I wrote that could be made part of the (extended) documentation:

- https://medium.com/jaegertracing/running-jaeger-agent-on-bare-metal-d1fc47d31fab
- https://medium.com/jaegertracing/the-life-of-a-span-ee508410200b
- https://medium.com/jaegertracing/protecting-jaeger-ui-with-an-oauth-sidecar-proxy-34205cca4bb1
- https://medium.com/jaegertracing/protecting-the-collection-of-spans-1948d88682e5
- https://medium.com/jaegertracing/jaeger-and-multitenancy-99dfa1d49dc0
- https://medium.com/jaegertracing/deployment-strategies-for-the-jaeger-agent-1d6f91796d09

I could commit to move them over, if that's what we decide to do.

**Comment by tiffon** [comment]
It looks like most of the medium posts are archived. Is that intentional?

Joe
