### ISSUE TITLE
Document how a single ES cluster can hold multiple Jaeger instances

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/documentation#433]
## Requirement - what kind of business use case are you trying to solve?

We should better document how it is possible to use a single ES cluster for multiple Jaeger instances, each on its own index prefix. Basically, this:

```console
$ ./bin/elasticsearch

$ SPAN_STORAGE_TYPE=elasticsearch go run ./cmd/all-in-one --query.static-files=./jaeger-ui/packages/jaeger-ui/build --log-level=debug  --es.index-prefix=tenant-acme

$ SPAN_STORAGE_TYPE=elasticsearch go run ./cmd/all-in-one --query.static-files=./jaeger-ui/packages/jaeger-ui/build --log-level=debug  --es.index-prefix=tenant-globex
```

The first command should be executed on its own terminal. The second command will bring a Jaeger instance, storing spans for tenant "acme". Run `tracegen` to test, storing some 20 traces there (`$ go run ./cmd/tracegen -traces 20`). Then, stop the instance, and start one for "globex". No traces should be visible in the UI. Then, start again Jaeger for "acme", and all initial spans should be there.

**Comment by pavolloffay** [comment]
+1

As this is related to multitenancy which is often being asked we could have a separate page for it with references to existing blog posts and storage docs that "somehow" support multitenancy.
