### ISSUE TITLE
The "deployment page" link on the OpenTelemetry page is broken 

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/documentation#435]
## Requirement - what kind of business use case are you trying to solve?

Just trying to read the doc

## Problem - what in Jaeger blocks you from solving the requirement?

Clicking on the "deployment page" link at the bottom of https://www.jaegertracing.io/docs/1.19/opentelemetry/  results in a 404.

**Comment by yurishkuro** [comment]
fixing
