### ISSUE TITLE
Link checker fails in local build and does not run in Travis

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#437]
Broken link was found in #435. It would've been found by the link checker, but turns it out does not run as part of the CI.

However, we cannot enable it now because it fails with two other errors

```
htmltest started at 10:53:11 on public
========================================================================
docs/index.html
  hash does not exist --- docs/index.html --> #ZgotmplZ
  target does not exist --- docs/index.html --> 1.19/1.19d1.19o1.19c1.19s1.19/1.19
```

pointing to these two lines:

```
<link rel="canonical" href="#ZgotmplZ" />
...
    <a class="tag is-medium is-warning" href="1.19/1.19d1.19o1.19c1.19s1.19/1.19">
```

@lucperkins - any thoughts on how to avoid these bad links?

**Comment by lucperkins** [comment]
I'm no longer with CNCF. Could you take a look, @celestehorgan?

**Comment by celestehorgan** [comment]
Thanks @lucperkins! It's on my backlog.

**Comment by yurishkuro** [comment]
Duplicate of https://github.com/jaegertracing/documentation/issues/671
