### ISSUE TITLE
Add [Copy] button to code blocks

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#444]
For example, on the Getting Started page we have a docker command:

![image](https://user-images.githubusercontent.com/3523016/94888830-46634780-0448-11eb-8373-f704d72c3852.png)

It would be nice if the code blocks would automatically add a [Copy] button in the top right corner to copy the code snippet (or command) into the clipboard. 

The button should have a tooltip "Copy to clipboard" and when clicked it could change its title to "Copied".

@celestehorgan would you know how to do this?

**Comment by shreyagupta30** [comment]
Hi, @jpkrohling!
I am an outreachy applicant for this cohort. Can I contribute to this issue?

**Comment by jpkrohling** [comment]
Absolutely, go ahead!

**Comment by shreyagupta30** [comment]
Hi @jpkrohling,  I have opened a pull request #449 solving this issue. Kindly review it and let me know the required changes. Thanks :)

**Comment by jpkrohling** [comment]
Looks great! @yurishkuro had a further request there, but look great in general!

**Comment by shreyagupta30** [comment]
> Looks great! @yurishkuro had a further request there, but look great in general!

Thanks @jpkrohling!
I am looking into that request. :)
