### ISSUE TITLE
Clarify health check port for OpenTelemetry components

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/documentation#450]
The [documentation](https://www.jaegertracing.io/docs/1.20/opentelemetry/) current says:

```markdown
The differences are:

* Health check port changed to `13133`
* Not all current Jaeger flags are exposed (e.g. health check port)
* Exposed metrics
```

The health-check port doesn't seem to be correct. The closest to the old admin port is the new metrics port, which is at `8888`. Perhaps this could be rewritten as:

```markdown
The differences are that the admin ports (14269, 14270, 14271), including the health check, was removed in favor of a new metrics port (8888). The health check was removed.
```

Looking at the code, I can't really tell where the health check handler is added, hence the last part of the suggestion.

**Comment by jpkrohling** [comment]
cc @pavolloffay

**Comment by pavolloffay** [comment]
The HC port should be `13133` https://github.com/open-telemetry/opentelemetry-collector/tree/master/extension/healthcheckextension.

The change of admin port should be explicitly listed too.

**Comment by jpkrohling** [comment]
I see, didn't realize it was a code from the upstream collector. I was under the impression it was our old health check :-)

**Comment by pavolloffay** [comment]
In fact I think the OTEL collector uses Jaeger HC implementation :) (Or it was using before). 

This reminds me that before we switch to only OTEL build, it might be good to move code that is used by OTEL collector to its repo to avoid circular dependencies and then in Jaeger repository move the OTEL module to the main module.
