### ISSUE TITLE
Provide required metadata for all pages

### ISSUE THREAD

**Issue by lucperkins** [jaegertracing/documentation#46]
At the moment, there is *no* page-level metadata for OpenGraph, Twitter Cards, etc. enabled for the site. In order to be properly discoverable in search results, embeddable in tweets and Facebook posts, etc., this will need to change.

@yurishkuro I feel like this issue should be resolved *before* the DNS switch for jaegertracing.io.

**Comment by yurishkuro** [comment]
agree that we should have it, no strong feeling why it needs to be done before DNS switch.
