### ISSUE TITLE
Reconsider transparency usage on the Jaeger Logo

### ISSUE THREAD

**Issue by nlowe** [jaegertracing/documentation#463]
## Requirement - what kind of business use case are you trying to solve?

Somebody linked to the Jaeger documentation in slack recently and I noticed that the logo looks...interesting against the slack dark background:

![image](https://user-images.githubusercontent.com/794251/101403876-b4821b80-388a-11eb-98b8-688bfdd3fc70.png)

This is really easy to notice by viewing the raw link of [`./static/img/jaeger-icon-color.png`](https://raw.githubusercontent.com/jaegertracing/documentation/master/static/img/jaeger-icon-color.png) with the OS using a dark theme and chrome set to inherit it:

![image](https://user-images.githubusercontent.com/794251/101403995-df6c6f80-388a-11eb-9023-78dcf0e36cdb.png)

## Problem - what in Jaeger blocks you from solving the requirement?

This is just a documentation / iconography issue, not a problem with Jaeger itself.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Certain areas of the Jaeger logo probably shouldn't be transparent.

**Comment by yurishkuro** [comment]
Could you show the full context of how a docs link look in Slack?

For example, posting on Facebook while in dark skin seems to work (now sure if FB uses a different image)

![image](https://user-images.githubusercontent.com/3523016/101407764-5e70a080-38a9-11eb-9c0c-49e7d1b7b1a9.png)

**Comment by nlowe** [comment]
So it looks like the link was just to the home page (`https://www.jaegertracing.io/`) and not the docs site, so I'm not sure if this repo is still the right place for this issue:

![image](https://user-images.githubusercontent.com/794251/101408039-a20ae080-3890-11eb-9114-d6a8a17a34c3.png)

I'm using the default dark theme in slack.

**Comment by yurishkuro** [comment]
Homepage is also in this repo. As far as I can tell, Facebook is using the same transparent image, but manages to display it correctly.
```
<meta name="og:image" content="https://www.jaegertracing.io/img/jaeger-icon-color.png">
```
I'd say we should create a non-transparent copy of the icon and refer to it in the meta tag to avoid this problem.

**Comment by SaarthakMaini** [comment]
I have made a non-transparent copy of the icon

Please review the same 
![Jaeger_Updated_Image](https://user-images.githubusercontent.com/94912101/219292212-f33b4e4f-1cc4-4ec1-8e88-b23866a4bd55.png)

**Comment by yurishkuro** [comment]
According to CNCF artwork repo this is already fixed for Jaeger. See here on black background: https://github.com/cncf/artwork/blob/master/projects/jaeger/jaeger-logo-guide.pdf

If there is still an issue with jaegertracing.io website, we probably just need to update the image in this repo from the official artwork.

Sorry @SaarthakMaini, I prefer not to use a hand-made unofficial logo. Can you check if https://github.com/cncf/artwork/tree/master/projects/jaeger already has what we need?

**Comment by yurishkuro** [comment]
Well, the question is whether we updated the image on the website to the newer version or not. We need to validate that it shows correctly in dark mode tools like Slack (e.g. cncf slack)

**Comment by yurishkuro** [comment]
I just tested in Slack and it comes out wrong, so we need to update the image in this repo.

![image](https://user-images.githubusercontent.com/3523016/219465275-d347dcfa-f07a-43ac-be65-9d45e28725fc.png)

**Comment by SaarthakMaini** [comment]
I double checked and the problem has been solved via Commit https://github.com/jaegertracing/documentation/commit/fd2eeae56e1d694fb30b694e07f63e0b5ce75417

![image](https://user-images.githubusercontent.com/94912101/219547597-47941714-d482-4091-9fd2-840f883ce90c.png)

I think the following commit link would be good for reference:

https://github.com/jaegertracing/documentation/commit/3e6d207c689a85281ce111c9d86eba52b2d2b9ef

Thank You!
