### ISSUE TITLE
Add ILM documentation

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/documentation#471]
## Requirement - what kind of business use case are you trying to solve?

Add documentation relating to this PR: https://github.com/jaegertracing/jaeger/pull/2454

The changes should update the Elasticsearch deployment section, especially to Elasticsearch Rollover: https://www.jaegertracing.io/docs/1.21/deployment/#elasticsearch.

**Comment by bhiravabhatla** [comment]
@albertteoh  - I see an unclosed tag (<1>) at the beginning of few lines in elasticsearch section. Is this expected?

![image](https://user-images.githubusercontent.com/36130219/106699249-8447c680-6608-11eb-91a3-5afa895c8e73.png)

**Comment by albertteoh** [comment]
Yup, this is expected. It's hard to see but if you scroll across the `docker run...` command, you'll see a `# <1>`; which acts like a label that the comment. A clearer example of how this is used is here: https://www.jaegertracing.io/docs/1.21/operator/#understanding-custom-resource-definitions

**Comment by bhiravabhatla** [comment]
Oh okay, I removed them in my PR, let me add them back
