### ISSUE TITLE
Change information about TLS support for the query service

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/documentation#475]
In the page linked below, we state that TLS support for the query service is non-existing. For 1.22, we need to state that this is supported if all the pieces of the work done by @rjs211 are merged by then.

https://www.jaegertracing.io/docs/1.21/security/#browser-to-ui

**Comment by yurishkuro** [comment]
This was already done in https://github.com/jaegertracing/documentation/commit/3e3f229ceb3af5c65c8d40ba7aac5386b1dd0733

**Comment by tillig** [comment]
It appears the _text_ on that change didn't get fixed - the green check says it's available, but the text still says "no TLS/authentication" next to it, which is super confusing.

**Comment by yurishkuro** [comment]
@tillig good catch. I think TLS is "yes", but the authentication is still No, right?

Would you like to submit a patch to the docs?
