### ISSUE TITLE
Change official channel to CNCF Slack #jaeger instead of Gitter

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/documentation#478]
During the past few sync calls, we decided to move from Gitter to the #jaeger channel at the CNCF Slack. The website needs to be changed to reflect that.

New link: https://cloud-native.slack.com/archives/CGG7NFUJ3

**Comment by yurishkuro** [comment]
I don't fully understand Slack URLs, but at least in OTEL there is another URL https://slack.cncf.io/ for people who do not have a CNCF Slack account yet.

**Comment by jpkrohling** [comment]
There's no notion of public workspaces in Slack, everyone has to have an invitation in order to join a workspace. The slack.cncf.io link will create an invitation and forward the request to the CNCF workspace at Slack. For folks who are in the workspace already, my link will send them directly to the Jaeger room.

**Comment by albertteoh** [comment]
I believe this issue has been addressed in #487.
