### ISSUE TITLE
should be of type string

### ISSUE THREAD

**Issue by lliuhaomin** [jaegertracing/documentation#484]
Building sites … WARN 2021/03/19 17:13:44 .File.Path on zero object. Wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}
Built in 368 ms
Error: Error building site: "D:\workResource\workRecode\2021.3.19 hugo\documentation-release-1.22.0\content\docs\1.14\cli.md:13:1": failed to render shortcode "cli/tools-list": failed to process shortcode: "D:\workResource\workRecode\2021.3.19 hugo\documentation-release-1.22.0\themes\jaeger-docs\layouts\shortcodes\cli\tools-list.html:4:15": execute of template failed: template: shortcodes/cli/tools-list.html:4:15: executing "shortcodes/cli/tools-list.html" at <index site.Data.cli $version>: error calling index: value is nil; should be of type string

**Comment by yurishkuro** [comment]
Which Hugo version?

**Comment by lliuhaomin** [comment]
0.65

![image](https://user-images.githubusercontent.com/34017007/111927042-30c30680-8aea-11eb-8af7-ebca2c1dc039.png)

**Comment by yurishkuro** [comment]
Could be Winwows-related, we do not support building docs on Windows.

I tried latest hugo, works fine on Mac:
```
$ hugo version
hugo v0.82.0+extended darwin/amd64 BuildDate=unknown

$ make develop
HUGO_PREVIEW=true hugo server \
        --buildDrafts \
        --buildFuture \
	--ignoreCache
Start building sites …
WARN 2021/03/21 20:57:33 .File.Path on zero object. Wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}

                   | EN
-------------------+------
  Pages            | 305
  Paginator pages  |   0
  Non-page files   |   0
  Static files     |  23
  Processed images |   0
  Aliases          |   0
  Sitemaps         |   1
  Cleaned          |   0

Built in 3523 ms
Watching for changes in /jaegertracing/documentation/{content,data,static,themes}
Watching for config changes in /jaegertracing/documentation/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by lliuhaomin** [comment]
Just look at the website effect, you can start it with docker

The command is as follows：

`docker run -v $PWD/documentation:/src -p 1313:1313 klakegg/hugo:0.82.0-ext-alpine server --disableFastRender --bind="0.0.0.0" --baseUrl="192.168.0.41"`
