### ISSUE TITLE
UI Configuration Docs - Out of date

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/documentation#493]
## Requirement - what kind of business use case are you trying to solve?

Help operators of Jaeger know how the UI can be configured

## Problem - what in Jaeger blocks you from solving the requirement?

The UI configuration section of the docs are out of date.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Update the docs to reflect how the UI can be configured.

**Comment by albertteoh** [comment]
Related issue: #489

**Comment by yurishkuro** [comment]
Closing as duplicate
