### ISSUE TITLE
Code copy feature includes command prompt in copy.

### ISSUE THREAD

**Issue by obasekiosa** [jaegertracing/documentation#495]
## Requirement - what kind of business use case are you trying to solve?
This is a user experience-related issue.

## Problem - what in Jaeger blocks you from solving the requirement?

Going through the [getting started page](https://www.jaegertracing.io/docs/1.22/getting-started/), the user may simply want to directly copy and paste the written [code](https://www.jaegertracing.io/docs/1.22/getting-started/#from-docker) using the copy button.
This is not possible because the command prompt symbol is also copied with the code, requiring the user to manually edit the copied text to prevent errors if directly pasted.
This defeats the purpose of the copy functionality.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Separate the prompt symbol display from the actual command, so the copy works as normal.

**Comment by yurishkuro** [comment]
I agree, I also found it annoying. I don't know how easy it is to display the prompt symbol via css, the simple alternative is to just remove it from the command.

**Comment by albertteoh** [comment]
+1 to just remove the `$` prompt symbol. 

I think the prompt symbol is useful to differentiate the command from the stdout, but in the case of the getting started page, these are only commands.
