### ISSUE TITLE
Automated release failing

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/documentation#505]
The automated release failed and seems to have been failing for quite some time, apparently because the script can't push directly to master (correctly), and because changes require one review before being merged (also correctly). Therefore, I generated the docs locally. We need to figure out what to do in the future: make the release script generate the pull request vs. push directly to master.

_Originally posted by @jpkrohling in https://github.com/jaegertracing/documentation/issues/504#issuecomment-855695157_

**Comment by pavolloffay** [comment]
done in #514 and #512
