### ISSUE TITLE
Side menu doesn't fit on 13' screens.

### ISSUE THREAD

**Issue by gquintana** [jaegertracing/documentation#508]
**Describe the bug**
The documentation menu doesn't fit on 13' screens.

**To Reproduce**

1.  Use a 13' laptop screen to view https://www.jaegertracing.io/docs/1.23/ website
2. The side menu doesn't fit in height 
<img width="948" alt="jaegertracingdoc-1" src="https://user-images.githubusercontent.com/755587/123662654-f3cb8600-d835-11eb-8819-94ce02244584.png">

3. It's not possible to scroll to see the bottom because the footer hides it 
<img width="947" alt="jaegertracingdoc-2" src="https://user-images.githubusercontent.com/755587/123662559-e0b8b600-d835-11eb-9c66-3d1d6bb66b34.png">

**Expected behavior**
See all the menu and be able to navigate in the documentation

**Screenshots**
See above

**Version (please complete the following information):**
 - OS: Windows
 - Jaeger version: 1.23
 - Deployment: Firefox

**Comment by yurishkuro** [comment]
Similar to #360

**Comment by gquintana** [comment]
Looks good. Thanks @yurishkuro
