### ISSUE TITLE
Operator docs warning

### ISSUE THREAD

**Issue by esnible** [jaegertracing/documentation#509]
(I am not sure if this request should apply to this repo, or https://github.com/jaegertracing/jaeger-operator , or both).

I am trying the operator doc, https://www.jaegertracing.io/docs/1.23/operator/ , for the first time.

Attempting to install the operator, the second line gives me grief:

```bash
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml # <2>

Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/jaegers.jaegertracing.io created
```

I am using K8s server version 1.19, client 1.20.

## Requirement - what kind of business use case are you trying to solve?

This is just an enhancement request, to keep the instructions working with K8s 1.22.

## Problem - what in Jaeger blocks you from solving the requirement?

No problem.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

No idea.

## Any open questions to address

It would be nice if the code snippet wasn't so wide, so I could see more of it.

**Comment by albertteoh** [comment]
@jpkrohling ☝🏼

**Comment by jpkrohling** [comment]
@rubenvp8510, was this warning addressed in the latest commits? Given that the older APIs got removed from the operator, it might be a good time to bump the CRD apiVersion.
