### ISSUE TITLE
Improvement of agent and collector tags documentation

### ISSUE THREAD

**Issue by pbdger** [jaegertracing/documentation#519]
Improvement of agent and collector tags documentation

## Problem - what in Jaeger blocks you from solving the requirement?

There is no description in the CLI documentation (https://www.jaegertracing.io/docs/1.25/cli/) that environment variables and their value can also be accessed for the agent and collector tags.

The deployment documentation (https://www.jaegertracing.io/docs/1.25/deployment/#agent-level-tags) describes this feature.

I suggest to include this feature documentation in the CLI documentation as well. Alternatively, you could also link to the deployment documentation in the CLI documentation.

**Comment by albertteoh** [comment]
@pbdger, I believe the CLI docs are intentionally meant to be quite general and apply to all CLI parameters. 

https://www.jaegertracing.io/docs/1.25/deployment/#agent-level-tags provides guidance on a capability that is specific to the `--agent.tags` flag, i.e. making environment variables accessible from a flag value.

As such, I think the documentation here is appropriate unless if I misunderstood something and if so, please provide a PR and we can discuss your suggestion there.

**Comment by yurishkuro** [comment]
no longer supported in v2
