### ISSUE TITLE
Outdated info in docs?

### ISSUE THREAD

**Issue by Saad-Hussain1** [jaegertracing/documentation#525]
**Describe the bug**
On https://www.jaegertracing.io/docs/1.26/security/ for client to collector, it says there's no TLS supported. However in the [CHANGELOG for 1.22](https://github.com/jaegertracing/jaeger/blob/master/CHANGELOG.md#1220-2021-02-23) and [this PR](https://github.com/jaegertracing/jaeger/pull/2798) specifically, it says TLS support was added. Am I misunderstanding something or is the doc outdated?

**To Reproduce**
n/a

**Expected behavior**
Docs mention ability to support HTTPS/mTLS for client -> collector

**Screenshots**
n/a

**Version (please complete the following information):**
n/a

**What troubleshooting steps did you try?**
n/a

**Additional context**
n/a

**Comment by yurishkuro** [comment]
I think there's certainly room for improvement in the docs here. I think you're correct that HTTP with TLS is not supported, assuming that the SDKs can work with https server URLs. And for mTLS there's even more requirements on the clients, even though on the server it is supported.
