### ISSUE TITLE
Style of inline code fragments is too strong

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#53]
[![](https://api.gh-polls.com/poll/01CAGNT68B9AQ6SQ21HK4H7ZG2/Magenta%20with%20background)](https://api.gh-polls.com/poll/01CAGNT68B9AQ6SQ21HK4H7ZG2/Magenta%20with%20background/vote)
[![](https://api.gh-polls.com/poll/01CAGNT68B9AQ6SQ21HK4H7ZG2/Black%20without%20background)](https://api.gh-polls.com/poll/01CAGNT68B9AQ6SQ21HK4H7ZG2/Black%20without%20background/vote)

This is just my preference, but I feel the current style for inline code fragments (grey background and magenta color) is too strong / distracting. It's especially evident on the client-features page where it introduces colors in the Feature column when it's not really needed. I've been experimenting with removing the color & bg on different pages, e.g.

![image](https://user-images.githubusercontent.com/3523016/38458675-d3454b18-3a6e-11e8-9962-7229dabacab9.png)

vs.

![image](https://user-images.githubusercontent.com/3523016/38458678-dd99bdf6-3a6e-11e8-9864-de3e71d3ba6f.png)

This is just for inline fragments, the code blocks using magenta are fine.

**Comment by yurishkuro** [comment]
/poll "Magenta w/ background" "Black without background"

**Comment by yurishkuro** [comment]
@lucperkins @jpkrohling @objectiser @black-adder @vprithvi @tiffon + all - vote in the poll

**Comment by objectiser** [comment]
Have checked the client features page and I am fine with current colour. But if others want to also change to black text then no problem.

**Comment by tiffon** [comment]
I also think the current styling has a bit too much contrast. I do like having a background, though, e.g. 

<img width="616" alt="screen shot 2018-04-07 at 11 43 30 pm" src="https://user-images.githubusercontent.com/2304337/38462999-aa3f415c-3abd-11e8-8b45-1b51a8dca438.png">

```css
code {
    background: #f5f5f5;
    color: #000;
    border: 1px solid #e8e8e8;
    border-bottom: 1px solid #e0e0e0;
    padding: 0.2em;
}
```

**Comment by lucperkins** [comment]
@tiffon By the way, here's a screenshot of your suggested CSS in action:

<img width="1030" alt="screen shot 2018-04-08 at 9 31 32 am" src="https://user-images.githubusercontent.com/1523104/38469823-bdb33df4-3b0f-11e8-9d63-18a0bd71e25b.png">

**Comment by tiffon** [comment]
Looks great!

**Comment by jpkrohling** [comment]
I vote for @tiffon's version
