### ISSUE TITLE
Broken links for jaegerdocs v1.18

### ISSUE THREAD

**Issue by kurianbenoy-sentient** [jaegertracing/documentation#559]
**Describe the bug**

In the page to install [Operator in Jaeger](https://www.jaegertracing.io/docs/1.18/operator/#installing-the-operator-on-kubernetes) there are broken links.
**To Reproduce**
1. [Go to page](https://www.jaegertracing.io/docs/1.18/operator/#installing-the-operator-on-kubernetes)
2. Run the command:
```
kubectl create namespace observability # <1>
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/main/deploy/crds/jaegertracing.io_jaegers_crd.yaml # <2>
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/main/deploy/service_account.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/main/deploy/role.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/main/deploy/role_binding.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/main/deploy/operator.yaml

```

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - OS: [e.g. Linux]
 - Jaeger version: [e.g. 1.8]
 - Deployment: [e.g. bare metal, Docker, Kubernetes, ...]

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

**Comment by yurishkuro** [comment]
I see that recent docs switched to using links like https://github.com/jaegertracing/jaeger-operator/releases/download/v1.32.0/jaeger-operator.yaml

v1.18 is almost 2yrs old, I don't see us fixing it. Please upgrade.

**Comment by kurianbenoy-sentient** [comment]
Ok @yurishkuro . Google SEO was pointing me to this version when I searched jaegertracing docs
