### ISSUE TITLE
Jaeger Operator manifest points to unreleased versions

### ISSUE THREAD

**Issue by iblancasa** [jaegertracing/documentation#580]
**Describe the bug**
The [Jaeger Operator documentation points](https://www.jaegertracing.io/docs/latest/operator/#installing-the-operator-on-kubernetes) to the manifest file to install it in a Kubernetes cluster. When a new Jaeger release is done, the documentation points to the manifest associated with the Jaeger version. This is a problem because that Jaeger Operator file will not exists until a new release of the Jaeger Operator is done.

For instance, latest Jaeger release is 1.35 and latest Jaeger Operator is version is 1.34.1. The Jaeger documentation points to `https://github.com/jaegertracing/jaeger-operator/releases/download/v1.35.0/jaeger-operator.yaml` but that file doesn't exist yet.

**Comment by SaarthakMaini** [comment]
I think the Operator should be changed to not depend on the exact Jaeger version. Is this issue still open?
