### ISSUE TITLE
[Bug]: Typo in the Operator install docs

### ISSUE THREAD

**Issue by robotfood** [jaegertracing/documentation#593]
### What happened?

In the installation docs for the Operator, the phrase "environmebt variable" has a typo in two places. 

### Steps to reproduce

- Navigate to https://www.jaegertracing.io/docs/1.39/operator/
- Read Installing the Operator on Kubernetes

### Expected behavior

"environmebt" should be spelled "environment"

### Screenshot

<img width="1294" alt="Screenshot 2022-11-06 at 1 01 25 PM" src="https://user-images.githubusercontent.com/1036093/200187223-36d9a48b-967a-4ef1-b049-dc62ede61097.png">

### Additional context

I can create a PR to fix this myself and link to this issue.

### Jaeger backend version

v1.39.0

**Comment by yurishkuro** [comment]
thanks for reporting
