### ISSUE TITLE
[Feature]: Document agent and open-telemetry OTLP clarification

### ISSUE THREAD

**Issue by matejsp** [jaegertracing/documentation#608]
### Requirement

We are using agent collector setup using jaeger native format. 
We saw that https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.16.0 deprecated jaeger exporters.

### Problem

Only collector is able to receive OTLP. Agents cannot accept OTLP, so microservices need to connect and send directly to collector caching data in the running process (in case of python this is more costly memory and perf wise) not to mention the UDP nature of zero overhead if collector or agent is unable to process span.

Does this mean that agent is actually obsolete with OTLP and no longer needed.

### Proposal

Please update documentation for new OTLP distributed setup.

**Comment by yurishkuro** [comment]
@matejsp I added 3 PRs to address your points.

**Comment by matejsp** [comment]
Wow :D That was fast :) I really like how you added also images with OpenTelemetry agent/collector. Perfection!

**Comment by MUI-Pop** [comment]
Will OTEL collector receiver would also drop its support in receiving trace in jaeger_thrift format over UDP ? or is it just the SDK's and OTEL collector exporter ?
