### ISSUE TITLE
[Feature]: Use consistent naming for Jaeger components

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#612]
### Requirement

Documentation should sue consistent naming to refer to Jaeger components.

### Problem

Some pages are using the binary names like `**jaeger-ingester**`, which is our preferred way, but others still use capitalized component names, like "Jaeger Agent", "the Jaeger Agent".

### Proposal

Update all pages to the same nomenclature:
  * Always use the binary name, such as `**jaeger-agent**`, `**jaeger-collector**`, `**jaeger-query**`
  * Do not prefix them with "the"
  * Make plural forms by adding `s` after the bold portion, i.e. `**jaeger-collector**s` == **jaeger-collector**s
  * Similarly, make possessive forms by adding `'s` after the bold portion, i.e. `**jaeger-collector**'s` == **jaeger-collector**'s
  * The only exception is when the section header refers to just the component, as in Deployment page that has headers like `Collector`, `Agent`, etc. While we could change those too, this will break the existing hyperlinks, so it's not worth it.

Incorrect usages can be located with a grep:
```shell
grep -rine '[^-]agent' content/docs/next-release
grep -rine '[^-]collector' content/docs/next-release
grep -rine '[^-]query' content/docs/next-release
grep -rine '[^-]ingester' content/docs/next-release
```

**Comment by sandipanpanda** [comment]
Hi, I am new to the jaeger project and look forward to getting involved in the jaeger community. I would like to help fix this issue.

**Comment by yurishkuro** [comment]
@sandipanpanda feel free to send PRs. I recommend smaller changes, e.g. cleaning up one docs file at a time.

**Comment by yurishkuro** [comment]
Don't think this is fully done, I just fixed a few more instances in troubleshooting section in #630

**Comment by SaarthakMaini** [comment]
@yurishkuro , I see that you have also updated troubleshoot.md in 1.44 version of the docs. 

I have only changed the next-release portion of the docs. Should I change other versions of the docs as well? 

Thank You!

**Comment by yurishkuro** [comment]
I changed then-current version and the next. I think your changes to next have already been applied to new version. There's no need to go back and change old versions.
