### ISSUE TITLE
[Feature]: Add CLI and SPM documentation for passing bearer token to prometheus

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/documentation#624]
### Requirement

As a jaeger operator, I want to pass a bearer token from jaeger to prometheus, required for the SPM feature.

### Problem

I can not find documentation on this neither in https://www.jaegertracing.io/docs/1.43/cli/ nor https://www.jaegertracing.io/docs/1.43/spm/ even though it appears this capability was added in https://github.com/jaegertracing/jaeger/pull/4295.

### Proposal

Add both these [CLI documentation](https://www.jaegertracing.io/docs/1.43/cli/) and maybe a mention of this in the [SPM documentation](https://www.jaegertracing.io/docs/1.43/spm/).

**Comment by yurishkuro** [comment]
That PR was merged after 1.43 release, so it will be included in the next release in the CLI docs. Manual change to SPM docs would be needed if we want it there.

**Comment by albertteoh** [comment]
> That PR was merged after 1.43 release, so it will be included in the next release in the CLI docs. Manual change to SPM docs would be needed if we want it there.

Ah okay, I missed that, thanks Yuri. I think it would be useful to add it to SPM since the question has come up a number of times now.
