### ISSUE TITLE
[Feature]: Use darker background for topnav menu mouseover

### ISSUE THREAD

**Issue by pabitra0011** [jaegertracing/documentation#658]
### Requirement

It is a part of UI enhancement.

### Problem

Currently, when we hover over an element, its background changes to white, specifically the header's background, which doesn't create a very visible effect. To enhance the webpage's UI, it should be more prominently visible when we hover over a navigation element.

Screenshort:
![image](https://github.com/jaegertracing/jaeger-ui/assets/94389910/b1d917e1-cc97-4909-a549-59af002293a7)

### Proposal

When a user hover an Nav element it should change it color from black to color: #66cfe3;(primary color).
or 
Suggest me any other enhancement that can i do.

**Comment by AryanParashar24** [comment]
Hey i would be really happy to work on it can u assign it to me plz 😄

**Comment by yurishkuro** [comment]
feel free to submit a PR. We do not assign tickets.

**Comment by tico88612** [comment]
@yurishkuro Which background color do you prefer?

Before (#f5f5f5)
<img width="404" alt="image" src="https://github.com/jaegertracing/documentation/assets/17496418/15aed29b-92e0-400f-a27a-93769dcb0839">

#e5e5e5
<img width="339" alt="image" src="https://github.com/jaegertracing/documentation/assets/17496418/32c7a192-cba5-482e-8a59-15e0554061d7">

#d5d5d5
<img width="392" alt="image" src="https://github.com/jaegertracing/documentation/assets/17496418/7a3efaa6-792c-472f-94e4-af4edc7de385">

**Comment by yurishkuro** [comment]
Last one is good
