### ISSUE TITLE
Make headers linkable

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#674]
For some reason the headers behave differently in the docs pages and in the static pages. In the docs pages the headers have a `<a name=...` anchors and on mouse-over show a hashtag that can be used to get the URL pointing directly to the section

<img width="299" alt="image" src="https://github.com/jaegertracing/documentation/assets/3523016/42c5926f-ab25-4c0b-9baf-e094cccf2fdf">

But the static, non-docs pages don't have that, it's quite annoying, e.g. https://www.jaegertracing.io/mentorship-for-mentees/

**Comment by siddharth-sable** [comment]
Hello @yurishkuro, I would love to take this in.

**Comment by yurishkuro** [comment]
feel free

**Comment by tico88612** [comment]
Hi, @siddharth-sable 
Are you still working on this? I've looked into the problem and fixed it; if you hadn't, I'd have opened a PR.
