### ISSUE TITLE
Blog posts are missing images

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#677]
The summary of Medium blob posts used to show header images. Something must have changed on Medium.

<img width="680" alt="image" src="https://github.com/jaegertracing/documentation/assets/3523016/01de8316-8426-4419-aaa7-dbbfb31d53df">

**Comment by yurishkuro** [comment]
This blog post explains the issue https://medium.com/@kartikyathakur/getting-those-thumbnails-from-medium-rss-feed-183f74aefa8c

Its suggestion is to parse the images out of the description text. The main downside of that is that the thumbnail image is not always the first one in the article, Medium allows you to change that. Also, those images in the text might be very large, compared to the thumbnail images Medium used to return for RSS.

I am not sure if we can make it work directly from Hugo template as we do here: https://github.com/jaegertracing/documentation/blob/08b96a308be252c3eac4f592f732e512e59e4dbb/themes/jaeger-docs/layouts/index.html#L2

If not, we can always add a pre-processing step to Makefile, fix the JSON and then just run Hugo against static content. We could even download the images as part of the build and serve them statically from our website  (and perhaps resize them first).

**Comment by tico88612** [comment]
Hi @yurishkuro 

I think we can start by fixing the image issue. Currently, Medium's RSS cannot identify from the description which one is the thumbnail. Using the first image from the article as the thumbnail is a good solution. If there is no image, then use a default one (like this: https://github.com/jaegertracing/documentation/blob/82d6bdffd963069633b083d95b97ffb592b58aa9/static/img/jaeger-icon-color.png). What do you think?

**Comment by yurishkuro** [comment]
ok
