### ISSUE TITLE
Move Badger migration instructions to another doc

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#682]
This section https://www.jaegertracing.io/docs/1.55/deployment/#badger---local-storage contains a large subsection related to Badger v1->v3 migration. It does not need to be in the docs. I suggest moving it to a an .md file in the `jaeger` repository inside Badger directories and link from the docs.

**Comment by tico88612** [comment]
Would it be better to move the `Badger v1->v3 migration` subsection to `jaeger` repository `plugin/storage/badger/README.md`? Or do you have any better suggestions?

https://github.com/jaegertracing/jaeger/tree/main/plugin/storage/badger/README.md

**Comment by yurishkuro** [comment]
I would move to its own file next to README. Can be linked from README.

**Comment by tico88612** [comment]
Could I open a PR and put it on the jaeger?

**Comment by yurishkuro** [comment]
sure

**Comment by tico88612** [comment]
Please feel free to take a look at it.

**Comment by tico88612** [comment]
Do I need to update the latest version of the documents, or should I update all documents after version 1.23?

**Comment by yurishkuro** [comment]
just the latest
