### ISSUE TITLE
Document Badger file permissions as non-root service.

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#683]
Solution is described here: https://github.com/jaegertracing/jaeger/issues/4906#issuecomment-1991779425

This can go to an `.md` file in `jaeger` repo inside Badger directory and linked from the docs https://www.jaegertracing.io/docs/1.55/deployment/#badger---local-storage

**Comment by tico88612** [comment]
PR has been opened at jaeger repo.
Please feel free to take a look at it.
