### ISSUE TITLE
[Feature]: Create GitHub Action to block PRs from ${fork}/main branch 

### ISSUE THREAD

**Issue by varshith257** [jaegertracing/documentation#687]
### Requirement

We should set up a new workflow that will fail if the PR is submitted from main branch. This workflow should be added to jearger/jarger-ui/documentation repositories (perhaps we need a reusable action - only if the check logic is reasonably complex).

### Problem

Making PR changes on the main branch of a fork is a bad practice, and breaks some of our workflows that check if the current branch is main before doing certain steps (like trying to push to Docker).

**Comment by varshith257** [comment]
Will update on it

**Comment by yurishkuro** [comment]
Please link to main issue (you didn't need a new ticket in the docs repo).
