### ISSUE TITLE
[Feature]: Left menu enhancement

### ISSUE THREAD

**Issue by tico88612** [jaegertracing/documentation#693]
### Requirement

This issue picks up where #690 left off.

Start at here: https://github.com/jaegertracing/documentation/pull/690#issuecomment-2036098330

### Problem

Change the style of the left menu to match the navigation bar above.

This video is an example:

https://github.com/jaegertracing/documentation/assets/17496418/75199015-8148-478e-8bfa-d6c5947e746d

**Comment by yurishkuro** [comment]
this might be addressed by the migration to docsy theme.
