### ISSUE TITLE
Add ability to search the documentation

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/documentation#70]
Sometimes I'm looking for a specific string inside the docs like a configuration flag. It'll be useful to be able to search for it somehow without having to dig through every page.

**Comment by yurishkuro** [comment]
+1

@lucperkins any idea what we can use for search?

**Comment by lucperkins** [comment]
@yurishkuro Personally, I'm *not* a fan of using external services like [Algolia](https://www.algolia.com) unless absolutely necessary. I can start putting something together that uses Hugo-generated JSON.

**Comment by yurishkuro** [comment]
How does this work? https://kubernetes.io/docs/search/?q=grpc

It looks like standard google search results, although slightly different than https://www.google.com/search?q=grpc+site%3Akubernetes.io

**Comment by lucperkins** [comment]
@yurishkuro It looks like the k8s site uses Google Custom Search. That's one way of doing things, but I'm a bigger fan of just generating our own index and using that, as I'm working on in #72.

**Comment by yurishkuro** [comment]
@lucperkins seems like Google Custom Search is much easier to start with, this is the code it produced:
```
<script>
  (function() {
    var cx = '014887072282358859417:-1yvfpw-5ao';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>
```
But it probably still needs some HTML magic to be embedded.

**Comment by tiffon** [comment]
@lucperkins What don't you like about using an external service? From a consumer's perspective, I've used [algolia's search](https://community.algolia.com/docsearch/) on quite a few OSS docs sites and find it very useful.

Here is a screenshot from flow.org where I typed "maybe" into the search box. The results are the large dark area, which displays the results in an overlay (as opposed to a separate page like Google custom search).

![image](https://user-images.githubusercontent.com/2304337/48995762-48a33f00-f117-11e8-9555-3e6dbd7d95cd.png)

**Comment by lucperkins** [comment]
@tiffon I have no rock-hard objections and I think Algolia is quite nice as well. But those services always come with the risk that they’ll be acquired/acquihired and EOLed, leaving us in a position where we have to start from scratch. So I guess it’s more that I bear a prejudice in favor of non-third-party solutions, though not an absolute one.
