### ISSUE TITLE
[Bug]: fix spelling issues

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#701]
We spellcheck the content using `make spellcheck`, which uses a dictionary of words `scripts/cspell/project-words.txt`. However, this dictionary was seeded with some clearly misspelled words, at minimum those shown in the diff below. The goal is to fix the occurrences of those misspelled words in the main content (e.g. by finding them with `grep -rn {word} content/`) and remove them from the dictionary file.

```diff
--- a/scripts/cspell/project-words.txt
+++ b/scripts/cspell/project-words.txt
@@ -6,15 +6,12 @@ ashmita
 autoscale
 autoscaler
 bansal
-behaviour
 bohara
 bootcamp
-boths
 certfile
 changeme
 clickhouse
 cncf
-conrolled
 containerd
 cqlsh
 cqlshrc
@@ -22,9 +19,6 @@ daemonset
 datacenter
 datasource
 developercertificate
-dilligence
-distirbuted
-documentiing
 downsampling
 dropwizard
 dsoie
@@ -51,8 +45,6 @@ htpasswd
 ingester
 ingester's
 ingesters
-ingestor
-initialisation
 istio
 istio's
 jaegertracing
@@ -128,18 +120,15 @@ statefulset
 strimzi's
 struct
 tchannel
-telemtery
 thriftrw
 tolerations
 tracegen
-trft
 uberctx
 unmarshaling
 upsample
 usercert
 userkey
 valuen
-variery
 vlog
 volz
 weaveworks
```

**Comment by priyanshsao** [comment]
does this issue is still present ? or has been solved.

**Comment by priyanshsao** [comment]
the two words "telemtery","trft" are still on the file , does the words needs to be removed.

**Comment by yurishkuro** [comment]
@priyanshsao yes they should be removed from the dictionaries

**Comment by priyanshsao** [comment]
when i searched for the word "trft" i got these-

content/docs/1.16/operator.md:979:          name: jg-compact-trft
content/docs/1.17/operator.md:704:      name: zk-compact-trft
content/docs/1.17/operator.md:710:      name: jg-compact-trft
content/docs/1.17/operator.md:713:      name: jg-binary-trft
content/docs/1.17/operator.md:1145:          name: jg-compact-trft
content/docs/1.18/operator.md:720:      name: zk-compact-trft
content/docs/1.18/operator.md:726:      name: jg-compact-trft
content/docs/1.18/operator.md:729:      name: jg-binary-trft
content/docs/1.18/operator.md:1161:          name: jg-compact-trft
content/docs/1.19/operator.md:786:      name: zk-compact-trft
content/docs/1.19/operator.md:792:      name: jg-compact-trft
content/docs/1.19/operator.md:795:      name: jg-binary-trft
content/docs/1.19/operator.md:1229:          name: jg-compact-trft
content/docs/1.20/operator.md:786:      name: zk-compact-trft
content/docs/1.20/operator.md:792:      name: jg-compact-trft
content/docs/1.20/operator.md:795:      name: jg-binary-trft
content/docs/1.20/operator.md:1229:          name: jg-compact-trft
content/docs/1.21/operator.md:786:      name: zk-compact-trft
content/docs/1.21/operator.md:792:      name: jg-compact-trft
content/docs/1.21/operator.md:795:      name: jg-binary-trft
content/docs/1.21/operator.md:1229:          name: jg-compact-trft
content/docs/1.22/operator.md:786:      name: zk-compact-trft
content/docs/1.22/operator.md:792:      name: jg-compact-trft
content/docs/1.22/operator.md:795:      name: jg-binary-trft
content/docs/1.22/operator.md:1229:          name: jg-compact-trft
content/docs/1.23/operator.md:786:      name: zk-compact-trft
content/docs/1.23/operator.md:792:      name: jg-compact-trft
content/docs/1.23/operator.md:795:      name: jg-binary-trft
content/docs/1.23/operator.md:1229:          name: jg-compact-trft
content/docs/1.24/operator.md:786:      name: zk-compact-trft
content/docs/1.24/operator.md:792:      name: jg-compact-trft
content/docs/1.24/operator.md:795:      name: jg-binary-trft
content/docs/1.24/operator.md:1229:          name: jg-compact-trft
content/docs/1.25/operator.md:828:      name: zk-compact-trft
content/docs/1.25/operator.md:834:      name: jg-compact-trft
content/docs/1.25/operator.md:837:      name: jg-binary-trft
content/docs/1.25/operator.md:1271:          name: jg-compact-trft
content/docs/1.26/operator.md:828:      name: zk-compact-trft
content/docs/1.26/operator.md:834:      name: jg-compact-trft
content/docs/1.26/operator.md:837:      name: jg-binary-trft
content/docs/1.26/operator.md:1271:          name: jg-compact-trft
content/docs/1.27/operator.md:828:      name: zk-compact-trft
content/docs/1.27/operator.md:834:      name: jg-compact-trft
content/docs/1.27/operator.md:837:      name: jg-binary-trft
content/docs/1.27/operator.md:1271:          name: jg-compact-trft
content/docs/1.28/operator.md:828:      name: zk-compact-trft
content/docs/1.28/operator.md:834:      name: jg-compact-trft
content/docs/1.28/operator.md:837:      name: jg-binary-trft
content/docs/1.28/operator.md:1271:          name: jg-compact-trft
content/docs/1.29/operator.md:808:      name: zk-compact-trft
content/docs/1.29/operator.md:814:      name: jg-compact-trft
content/docs/1.29/operator.md:817:      name: jg-binary-trft
content/docs/1.29/operator.md:1251:          name: jg-compact-trft
content/docs/1.30/operator.md:808:      name: zk-compact-trft
content/docs/1.30/operator.md:814:      name: jg-compact-trft
content/docs/1.30/operator.md:817:      name: jg-binary-trft
content/docs/1.30/operator.md:1251:          name: jg-compact-trft
content/docs/1.31/operator.md:816:      name: zk-compact-trft
content/docs/1.31/operator.md:822:      name: jg-compact-trft
content/docs/1.31/operator.md:825:      name: jg-binary-trft
content/docs/1.31/operator.md:1259:          name: jg-compact-trft
content/docs/1.32/operator.md:816:      name: zk-compact-trft
content/docs/1.32/operator.md:822:      name: jg-compact-trft
content/docs/1.32/operator.md:825:      name: jg-binary-trft
content/docs/1.32/operator.md:1259:          name: jg-compact-trft
content/docs/1.33/operator.md:861:      name: zk-compact-trft
content/docs/1.33/operator.md:867:      name: jg-compact-trft
content/docs/1.33/operator.md:870:      name: jg-binary-trft
content/docs/1.33/operator.md:1304:          name: jg-compact-trft
content/docs/1.34/operator.md:861:      name: zk-compact-trft
content/docs/1.34/operator.md:867:      name: jg-compact-trft
content/docs/1.34/operator.md:870:      name: jg-binary-trft
content/docs/1.34/operator.md:1304:          name: jg-compact-trft
content/docs/1.35/operator.md:861:      name: zk-compact-trft
content/docs/1.35/operator.md:867:      name: jg-compact-trft
content/docs/1.35/operator.md:870:      name: jg-binary-trft
content/docs/1.35/operator.md:1304:          name: jg-compact-trft
content/docs/1.36/operator.md:861:      name: zk-compact-trft
content/docs/1.36/operator.md:867:      name: jg-compact-trft
content/docs/1.36/operator.md:870:      name: jg-binary-trft
content/docs/1.36/operator.md:1304:          name: jg-compact-trft
content/docs/1.37/operator.md:861:      name: zk-compact-trft
content/docs/1.37/operator.md:867:      name: jg-compact-trft
content/docs/1.37/operator.md:870:      name: jg-binary-trft
content/docs/1.37/operator.md:1304:          name: jg-compact-trft
content/docs/1.38/operator.md:861:      name: zk-compact-trft
content/docs/1.38/operator.md:867:      name: jg-compact-trft
content/docs/1.38/operator.md:870:      name: jg-binary-trft
content/docs/1.38/operator.md:1304:          name: jg-compact-trft
content/docs/1.39/operator.md:861:      name: zk-compact-trft
content/docs/1.39/operator.md:867:      name: jg-compact-trft
content/docs/1.39/operator.md:870:      name: jg-binary-trft
content/docs/1.39/operator.md:1304:          name: jg-compact-trft
content/docs/1.40/operator.md:861:      name: zk-compact-trft
content/docs/1.40/operator.md:867:      name: jg-compact-trft
content/docs/1.40/operator.md:870:      name: jg-binary-trft
content/docs/1.40/operator.md:1414:          name: jg-compact-trft
content/docs/1.41/operator.md:861:      name: zk-compact-trft
content/docs/1.41/operator.md:867:      name: jg-compact-trft
content/docs/1.41/operator.md:870:      name: jg-binary-trft
content/docs/1.41/operator.md:1414:          name: jg-compact-trft
content/docs/1.42/operator.md:861:      name: zk-compact-trft
content/docs/1.42/operator.md:867:      name: jg-compact-trft
content/docs/1.42/operator.md:870:      name: jg-binary-trft
content/docs/1.42/operator.md:1414:          name: jg-compact-trft
content/docs/1.43/operator.md:861:      name: zk-compact-trft
content/docs/1.43/operator.md:867:      name: jg-compact-trft
content/docs/1.43/operator.md:870:      name: jg-binary-trft
content/docs/1.43/operator.md:1414:          name: jg-compact-trft
content/docs/1.44/operator.md:861:      name: zk-compact-trft
content/docs/1.44/operator.md:867:      name: jg-compact-trft
content/docs/1.44/operator.md:870:      name: jg-binary-trft
content/docs/1.44/operator.md:1414:          name: jg-compact-trft
content/docs/1.45/operator.md:861:      name: zk-compact-trft
content/docs/1.45/operator.md:867:      name: jg-compact-trft
content/docs/1.45/operator.md:870:      name: jg-binary-trft
content/docs/1.45/operator.md:1414:          name: jg-compact-trft
content/docs/1.46/operator.md:861:      name: zk-compact-trft
content/docs/1.46/operator.md:867:      name: jg-compact-trft
content/docs/1.46/operator.md:870:      name: jg-binary-trft
content/docs/1.46/operator.md:1414:          name: jg-compact-trft
content/docs/1.47/operator.md:861:      name: zk-compact-trft
content/docs/1.47/operator.md:867:      name: jg-compact-trft
content/docs/1.47/operator.md:870:      name: jg-binary-trft
content/docs/1.47/operator.md:1414:          name: jg-compact-trft
content/docs/1.48/operator.md:861:      name: zk-compact-trft
content/docs/1.48/operator.md:867:      name: jg-compact-trft
content/docs/1.48/operator.md:870:      name: jg-binary-trft
content/docs/1.48/operator.md:1414:          name: jg-compact-trft
content/docs/1.49/operator.md:861:      name: zk-compact-trft
content/docs/1.49/operator.md:867:      name: jg-compact-trft
content/docs/1.49/operator.md:870:      name: jg-binary-trft
content/docs/1.49/operator.md:1414:          name: jg-compact-trft
content/docs/1.50/operator.md:861:      name: zk-compact-trft
content/docs/1.50/operator.md:867:      name: jg-compact-trft
content/docs/1.50/operator.md:870:      name: jg-binary-trft
content/docs/1.50/operator.md:1414:          name: jg-compact-trft
content/docs/1.51/operator.md:861:      name: zk-compact-trft
content/docs/1.51/operator.md:867:      name: jg-compact-trft
content/docs/1.51/operator.md:870:      name: jg-binary-trft
content/docs/1.51/operator.md:1414:          name: jg-compact-trft
content/docs/1.52/operator.md:861:      name: zk-compact-trft
content/docs/1.52/operator.md:867:      name: jg-compact-trft
content/docs/1.52/operator.md:870:      name: jg-binary-trft
content/docs/1.52/operator.md:1414:          name: jg-compact-trft
content/docs/1.53/operator.md:861:      name: zk-compact-trft
content/docs/1.53/operator.md:867:      name: jg-compact-trft
content/docs/1.53/operator.md:870:      name: jg-binary-trft
content/docs/1.53/operator.md:1414:          name: jg-compact-trft
content/docs/1.54/operator.md:861:      name: zk-compact-trft
content/docs/1.54/operator.md:867:      name: jg-compact-trft
content/docs/1.54/operator.md:870:      name: jg-binary-trft
content/docs/1.54/operator.md:1414:          name: jg-compact-trft
content/docs/1.55/operator.md:861:      name: zk-compact-trft
content/docs/1.55/operator.md:867:      name: jg-compact-trft
content/docs/1.55/operator.md:870:      name: jg-binary-trft
content/docs/1.55/operator.md:1414:          name: jg-compact-trft
content/docs/1.56/operator.md:861:      name: zk-compact-trft
content/docs/1.56/operator.md:867:      name: jg-compact-trft
content/docs/1.56/operator.md:870:      name: jg-binary-trft
content/docs/1.56/operator.md:1414:          name: jg-compact-trft
content/docs/1.57/operator.md:861:      name: zk-compact-trft
content/docs/1.57/operator.md:867:      name: jg-compact-trft
content/docs/1.57/operator.md:870:      name: jg-binary-trft
content/docs/1.57/operator.md:1414:          name: jg-compact-trft
content/docs/1.58/operator.md:825:      name: zk-compact-trft
content/docs/1.58/operator.md:831:      name: jg-compact-trft
content/docs/1.58/operator.md:834:      name: jg-binary-trft
content/docs/1.58/operator.md:1378:          name: jg-compact-trft
content/docs/1.59/operator.md:825:      name: zk-compact-trft
content/docs/1.59/operator.md:831:      name: jg-compact-trft
content/docs/1.59/operator.md:834:      name: jg-binary-trft
content/docs/1.59/operator.md:1378:          name: jg-compact-trft
content/docs/1.60/operator.md:825:      name: zk-compact-trft
content/docs/1.60/operator.md:831:      name: jg-compact-trft
content/docs/1.60/operator.md:834:      name: jg-binary-trft
content/docs/1.60/operator.md:1378:          name: jg-compact-trft
content/docs/1.61/operator.md:825:      name: zk-compact-trft
content/docs/1.61/operator.md:831:      name: jg-compact-trft
content/docs/1.61/operator.md:834:      name: jg-binary-trft
content/docs/1.61/operator.md:1378:          name: jg-compact-trft
content/docs/1.62/operator.md:825:      name: zk-compact-trft
content/docs/1.62/operator.md:831:      name: jg-compact-trft
content/docs/1.62/operator.md:834:      name: jg-binary-trft
content/docs/1.62/operator.md:1378:          name: jg-compact-trft
content/docs/next-release/operator.md:825:      name: zk-compact-trft
content/docs/next-release/operator.md:831:      name: jg-compact-trft
content/docs/next-release/operator.md:834:      name: jg-binary-trft
content/docs/next-release/operator.md:1378:          name: jg-compact-trft
content/docs/next-release-v2/operator.md:825:      name: zk-compact-trft
content/docs/next-release-v2/operator.md:831:      name: jg-compact-trft
content/docs/next-release-v2/operator.md:834:      name: jg-binary-trft
content/docs/next-release-v2/operator.md:1378:          name: jg-compact-trft

**Comment by priyanshsao** [comment]
does the word "trft" needs to be replaced with some other word or we just need to remove those two words from the dictionary.

**Comment by yurishkuro** [comment]
I think in those cases it can be replaced with `thrift`, because those are just arbitrary names that are supposed to be readable, and it looks like this was a typo.

**Comment by priyanshsao** [comment]
@yurishkuro, I just discovered that the word 'promethesus' is also present in the same file, which wasn't mentioned in this  issue. It appears to be misspelled and isn't used anywhere in the content folder . Should this be considered a typo that needs to be removed as well?

**Comment by yurishkuro** [comment]
Yes
