### ISSUE TITLE
Specifically call out that Sampler Const is not supported in remote

### ISSUE THREAD

**Issue by aaronkorver** [jaegertracing/documentation#71]
Well, I spent a few hours scratching my head on why my `type:const` was not being honored in the `strategies.json` file.  Then I dug into the code and saw it was because it isn't supported.  The Sampling page in the docs lists it as valid, but there is one line at the very bottom that just says 'ratelimiting' and 'probabilistic' are supported.  Would have saved me some frustration if this was more explicit.

However, I did learn more about the project by digging into the source code..so win-win?

**Comment by yurishkuro** [comment]
sorry about that - care to make it win-win-win by submitting a PR?  Where is it not supported, on the backend or in the clients?

**Comment by aaronkorver** [comment]
Yup, I'm planning on it.
https://github.com/jaegertracing/jaeger/blob/master/plugin/sampling/strategystore/static/strategy_store.go#L89 is the code that doesn't support using const in the remote sampling

**Comment by Falco20019** [comment]
It's not supported on both sides. Server does not have a field for it in `SamplingStrategyResponse` and therefore the clients won't parse it.
