### ISSUE TITLE
RSS feed is crashing the build

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#710]
https://github.com/jaegertracing/documentation/blob/097291d6dc05e53c3041b291f603ff16f0ef7f1b/themes/jaeger-docs/layouts/index.html#L3

We are trying to download RSS feed from Medium to convert it into blog post cards on the home page. Previously Hugo only supported parsing of JSON files, so we used a proxy website https://api.rss2json.com/v1/api.json to parse the XML feed output and return as JSON to Hugo. However, with recent changes the requests going through this site are randomly failing (I think because of cloudfare's no-robots check).

The actual call to https://medium.com/feed/jaegertracing seems more reliable. It returns XML, but Hugo can now parse XML. The only problem is that the structure of that XML (after being converted into a map of maps) is different from the previous JSON file, so our build still fails. The code needs to be adjusted to read different fields in the maps, like `content:encoded` instead of `content`, `.channel.item` instead of `.items`, etc.

**Comment by chamodshehanka** [comment]
@yurishkuro I would like to work on this
