### ISSUE TITLE
[Bug]: GitHub Action checkout v3 uses depracated version

### ISSUE THREAD

**Issue by chamodshehanka** [jaegertracing/documentation#715]
### What happened?

When every running github action get this warning message due to outdated checkout step

### Steps to reproduce

1. do a change in the code
2. Go to github action tab

### Expected behavior

GitHub Actions should run without any warning

### Relevant log output

```shell
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

### Screenshot

![image](https://github.com/jaegertracing/documentation/assets/19349315/e797022c-722c-41f3-b322-a440907d041d)

### Additional context

Documentation repo

**Comment by yurishkuro** [comment]
Instead of fixing this one manually we should enable dependabot for this repo.

**Comment by chamodshehanka** [comment]
> Instead of fixing this one manually we should enable dependabot for this repo.

That will be a good move
