### ISSUE TITLE
Why do we keep listing all ports in the Docker commands?

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#73]
[e.g. here](https://github.com/opentracing-contrib/python-flask/pull/12/files#diff-20bfc3ff6a860483887b93bf9cf0d135R16):
```
docker run -d -e \
+  COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
+  -p 5775:5775/udp \
+  -p 6831:6831/udp \
+  -p 6832:6832/udp \
+  -p 5778:5778 \
+  -p 16686:16686 \
+  -p 14268:14268 \
+  -p 9411:9411 \
+  jaegertracing/all-in-one:latest
```

Why do we recommend that instead of just running on host network?

@pavolloffay @jpkrohling

**Comment by pavolloffay** [comment]
I am personally using host network, even though it's not recommended. 

This explicit listing makes it clear which ports are used. It's also easier to change a port is there is a collision.

**Comment by yurishkuro** [comment]
Exactly. It makes me cringe when I see those 10-line commands in people's blogs. In our docs we can list both ways.

For the grpc work I intend to make everything run on a single port.

**Comment by jpkrohling** [comment]
> For the grpc work I intend to make everything run on a single port.

This would be an awesome improvement! Instead of just a single port, do consider using two: one to be exposed to the internal network only (like the healthcheck endpoints) and one for the "public" network, like span collection.

**Comment by joepio** [comment]
The `docker run -P` flag can be used to use to bind all the `EXPOSE`d ports.  For the all-in-one-image, I think having a shorter command is preferable. I'd suggest the docs should use:

`docker run -P jaegertracing/all-in-one`

However, this requires that the all-on-one `dockerfile` uses `EXPOSE` for all ports - currently it only does it for specific ones.

**Comment by frzifus** [comment]
Oh thats good to know. But it seems it allocates some random port numbers and forwards traffic to the exposed ports?

Ports:
```
0.0.0.0:49158->5775/udp
0.0.0.0:49158->14268/tcp
0.0.0.0:49159->14250/tcp
0.0.0.0:49157->16686/tcp
```

Output:
```bash
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS         PORTS                                                                                                                                                                                                                                                                                                                             NAMES
cafd0e3c07da   jaegertracing/all-in-one   "/go/bin/all-in-one-…"   5 seconds ago   Up 4 seconds   0.0.0.0:49158->5775/udp, :::49158->5775/udp, 0.0.0.0:49160->5778/tcp, :::49160->5778/tcp, 0.0.0.0:49157->6831/udp, :::49157->6831/udp, 0.0.0.0:49156->6832/udp, :::49156->6832/udp, 0.0.0.0:49159->14250/tcp, :::49159->14250/tcp, 0.0.0.0:49158->14268/tcp, :::49158->14268/tcp, 0.0.0.0:49157->16686/tcp, :::49157->16686/tcp   kind_liskov
```

**Comment by joepio** [comment]
@frzifus sorry, you're right. `-P` is random. Edited my comment.
