### ISSUE TITLE
[jaeger-v2] Document changes to admin port / services

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#750]
* metrics are on a different port `address: 0.0.0.0:8888` (`address: 0.0.0.0:8889` for ingester)
* expvar is also on a different port via `expvar` extension: `port: 27777`
* Healthchecks are on a different port via `healthcheckv2` extension: `endpoint: "0.0.0.0:13133"`

**Comment by jkowall** [comment]
I did some updates to the docs per : https://github.com/jaegertracing/documentation/pull/751

The following seem to still be in the v1 docs and I believe should be somewhere in v2 docs, let me know what you think:

```
At default settings **jaeger-collector** exposes the following ports:

| Port  | Protocol | Endpoint | Function
| ----- | -------  | -------- | ----
| 4317  | gRPC     | n/a      | Accepts traces in [OpenTelemetry OTLP format][otlp] (Protobuf).
| 4318  | HTTP     | `/v1/traces` | Accepts traces in [OpenTelemetry OTLP format][otlp] (Protobuf and JSON).
| 14268 | HTTP     | `/api/sampling` | Serves sampling policies (see [Remote Sampling](../sampling/#remote-sampling)).
|       |          | `/api/traces` | Accepts spans in [jaeger.thrift][jaeger-thrift] format with `binary` thrift protocol (`POST`).
| 9411  | HTTP     | `/api/v1/spans` and `/api/v2/spans` | Accepts Zipkin spans in Thrift, JSON and Proto (disabled by default).
| 14250 | gRPC     | n/a      | Used by **jaeger-agent** to send spans in [model.proto][] Protobuf format.
```

**Comment by yurishkuro** [comment]
yes, those ports would still be relevant (sometimes the ports might be different)

**Comment by jkowall** [comment]
Is anything else pending on this issue or can we close @yurishkuro ?

**Comment by yurishkuro** [comment]
I plan to give a read of all new docs this w/e and then will close.
