### ISSUE TITLE
[Feature]: Making the Sidebar more interactive.

### ISSUE THREAD

**Issue by RithwikBejadi** [jaegertracing/documentation#758]
### Requirement

The Sidebar of the Webpages must look more interactive and attractive.

### Problem

Work on interaction of sidebar

### Proposal

I would like to improve the sidebar and make it more interactive and attractive.

**Comment by RithwikBejadi** [comment]
Please assign this issue to me under Hactoberfest. I would like to work on it

**Comment by yurishkuro** [comment]
no follow-up or concrete suggestions, so closing.
