### ISSUE TITLE
[v2] Features page should not contain full SPM

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#764]
https://www.jaegertracing.io/docs/next-release-v2/features/

**Comment by jkowall** [comment]
Will fix tomorrow morning

**Comment by yurishkuro** [comment]
The Features page is very heavy right now. I think it should provide brief introduction into various aspects, and refer to dedicated pages for long content like SPM. For example, why is SPM/Architecture relevant to the Features page?

**Comment by yurishkuro** [comment]
Similar issue with sampling #767
