### ISSUE TITLE
[Bug]: Incorrect URL to Jaeger Operator YAML File in Documentation

### ISSUE THREAD

**Issue by pradeeptac** [jaegertracing/documentation#768]
### What happened?

The documentation for installing the Jaeger Operator at https://www.jaegertracing.io/docs/1.62/operator/ contains incorrect URLs for the Jaeger Operator YAML file. The URL currently includes an extra ".0" at the end, which results in a 404 error when used.

URL provided in documentation: https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0.0/jaeger-operator.yaml
should be URL: https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0/jaeger-operator.yaml

### Steps to reproduce

1. Visit the [Installing the Operator on Kubernetes](https://www.jaegertracing.io/docs/1.62/operator/#installing-the-operator-on-kubernetes) section.
Run the provided command:
`
kubectl create namespace observability # <1>
kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0.0/jaeger-operator.yaml -n observability # <2>
`
2. Try to access this URL in a browser or through kubectl. Error:
`
% kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0.0/jaeger-operator.yaml -n observability
error: unable to read URL "https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0.0/jaeger-operator.yaml", server reported 404 Not Found, status code=404
`

### Expected behavior

The command should use the correct URL without the extra ".0" at the end:

`
kubectl create namespace observability # <1>
kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0/jaeger-operator.yaml -n observability # <2>
`

### Relevant log output

`
% kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0.0/jaeger-operator.yaml -n observability
error: unable to read URL "https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0.0/jaeger-operator.yaml", server reported 404 Not Found, status code=404
`

### Additional context

This change needs to be made at the following locations:

[Installing the Operator on Kubernetes](https://www.jaegertracing.io/docs/1.62/operator/#installing-the-operator-on-kubernetes)

`
kubectl create namespace observability # <1>
kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0.0/jaeger-operator.yaml -n observability # <2>
`
Change the URL to:
`
kubectl create namespace observability # <1>
kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0/jaeger-operator.yaml -n observability # <2>
`

[Installing the Operator on OKD/OpenShift](https://www.jaegertracing.io/docs/1.62/operator/#installing-the-operator-on-okdopenshift)

`
oc new-project observability # <1>
oc create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0.0/jaeger-operator.yaml -n observability # <2>
`
Change the URL to:
`
oc new-project observability # <1>
oc create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0/jaeger-operator.yaml -n observability # <2>
`

[Uninstalling the Operator](https://www.jaegertracing.io/docs/1.62/operator/#uninstalling-the-operator)

`
kubectl delete -n observability -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0.0/jaeger-operator.yaml
`
Change the URL to:
`
kubectl delete -n observability -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0/jaeger-operator.yaml
`

### Jaeger backend version

v1.62.0

### Deployment model

Kubernetes

### Deployment configs

k8s manifest

**Comment by yurishkuro** [comment]
The doc is using `currentVersion` shortcut (which already comes as major.minor.patch) and incorrectly adds a trailing `.0`, e.g.
`kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v{{< currentVersion >}}.0/jaeger-operator.yaml -n observability # <2>`
