### ISSUE TITLE
[v2] Add internal architecture diagram

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#777]
The [Architecture](https://www.jaegertracing.io/docs/2.0/architecture/) page shows diagrams of different deployments, but is missing a diagram for internal architecture of jaeger-v2 binary, similar to [this one](https://github.com/jaegertracing/jaeger/tree/main/cmd/jaeger#jaeger), but with more details.

It must include
  * extensions
    * jaeger_query
    * jaeger_storage
    * remote_sampling
  * exporters
    * jaeger_storage_exporter (which uses sanitizers - might be too much detail)
  * processors
    * adaptive_sampling

## Open Questions
* The Configuration page currently contains a description of some components, should those be moved into Architecture?

**Comment by jkowall** [comment]
What kind of additional detail do you envision for this?

**Comment by yurishkuro** [comment]
Literally the diagram from the readme but showing all standard v2 components / extensions.

**Comment by jkowall** [comment]
I'll have a go tomorrow from the flights.
