### ISSUE TITLE
[Bug]: Outdated link at Docs -> Introduction

### ISSUE THREAD

**Issue by jourteen** [jaegertracing/documentation#781]
### What happened?

The link named _Learning Distributed Tracing 101_ redirects to the home page of https://rxdb.info instead of tutorials.

### Steps to reproduce

1. Go to https://www.jaegertracing.io
2. In the main menu: Docs -> Introduction
3. In the Related Links section click _Learning Distributed Tracing 101_

### Expected behavior

The link leads to distributed tracing tutorials or no link at all.

### Relevant log output

```shell

```

### Deployment configs

```shell

```

**Comment by yurishkuro** [comment]
Thanks for reporting
