### ISSUE TITLE
[Bug]: V2.1 Binary Download links are broken

### ISSUE THREAD

**Issue by MadVikingGod** [jaegertracing/documentation#817]
### What happened?

On the [Download page](https://www.jaegertracing.io/download/) the links to the Binary V2.1 all point to a release that doesn't exist.

They point to ht<span>tps://</span>github.com/jaegertracing/jaeger/releases/download/ **v2.1.0** /jaeger-2.1.0-linux-amd64.tar.gz when it should point to  ht<span>tps://</span>github.com/jaegertracing/jaeger/releases/download/ **v1.64.0** /jaeger-2.1.0-linux-amd64.tar.gz

### Steps to reproduce

1. Goto [Download page](https://www.jaegertracing.io/download/)
2. Click on any of the Binary V2.1 links
3. Get a `Not Found` page from github

### Expected behavior

1. Goto [Download page](https://www.jaegertracing.io/download/)
2. Click on any of the Binary V2.1 links
3. Get the correct download

### Relevant log output

```shell
N/A
```

### Deployment configs

```shell

```

**Comment by yurishkuro** [comment]
Thanks for reporting.
